In [ ]:
from google.colab import files

uploaded = files.upload()
print(uploaded.keys())

Saving final_regression_dataset_v1.xlsx to final_regression_dataset_v1.xlsx
dict_keys(['final_regression_dataset_v1.xlsx'])

In [ ]:
import pandas as pd
import numpy as np

file_name = list(uploaded.keys())[0]
file_path = f"/content/{file_name}"

reg = pd.read_excel(file_path, sheet_name="regression_base")
diag = pd.read_excel(file_path, sheet_name="diagnostics_desc")
macro = pd.read_excel(file_path, sheet_name="macro_zone_rates")

print(reg.shape)
reg.head()

(781, 29)

,firm_id,ticker,company_name,country,macro_zone,sector,fiscal_year,roa,roa_ebit,interest_coverage,...,revenue,ebit,ebitda,interest_expense,net_income,total_assets,total_debt,source_primary,data_quality_score,notes
0,F001,AAPL,Apple Inc.,United States,US,Technology,2022,0.282924,0.323701,40.749574,...,3.943280e+11,1.194370e+11,1.305410e+11,2.931000e+09,9.980300e+10,3.527550e+11,1.118240e+11,Yahoo + SEC override,1.000,NaN
1,F001,AAPL,Apple Inc.,United States,US,Technology,2023,0.275098,0.323701,29.062039,...,3.832850e+11,1.143010e+11,1.258200e+11,3.933000e+09,9.699500e+10,3.525830e+11,1.065720e+11,Yahoo + SEC override,1.000,NaN
2,F001,AAPL,Apple Inc.,United States,US,Technology,2024,0.256825,0.323701,NaN,...,3.910350e+11,1.232160e+11,1.346610e+11,NaN,9.373600e+10,3.649800e+11,9.734100e+10,Yahoo + SEC override,0.875,NaN
3,F001,AAPL,Apple Inc.,United States,US,Technology,2025,0.306894,0.323701,NaN,...,4.161610e+11,1.330500e+11,1.447480e+11,NaN,1.120100e+11,3.649800e+11,9.128100e+10,Yahoo + SEC override,0.875,NaN
4,F002,MSFT,Microsoft Corporation,United States,US,Technology,2022,0.121371,0.145157,20.439599,...,1.430150e+11,5.295900e+10,1.002390e+11,2.591000e+09,4.428100e+10,3.648400e+11,5.551100e+10,Yahoo + SEC override,1.000,NaN

In [ ]:
s = reg["interest_coverage"].dropna()

print("Min:", s.min())
print("P1:", s.quantile(0.01))
print("Median:", s.median())
print("P99:", s.quantile(0.99))
print("Max:", s.max())

Min: -597.3913043478261
P1: -3.974792574809226
Median: 11.080523274274466
P99: 806.6476085434132
Max: 16438.81481481481

In [ ]:
# on garde une copie brute
reg["interest_coverage_raw_backup"] = reg["interest_coverage"]

# seuils
lo = reg["interest_coverage"].quantile(0.01)
hi = reg["interest_coverage"].quantile(0.99)

# winsorisation
reg["interest_coverage"] = reg["interest_coverage"].clip(lower=lo, upper=hi)

print("Lower bound:", lo)
print("Upper bound:", hi)

changed = (
    (reg["interest_coverage_raw_backup"] < lo) |
    (reg["interest_coverage_raw_backup"] > hi)
).sum()

print("Nombre de lignes modifiées :", changed)

Lower bound: -3.974792574809226
Upper bound: 806.6476085434132
Nombre de lignes modifiées : 16

In [ ]:
s2 = reg["interest_coverage"].dropna()

print("Min après correction:", s2.min())
print("P1 après correction:", s2.quantile(0.01))
print("Median après correction:", s2.median())
print("P99 après correction:", s2.quantile(0.99))
print("Max après correction:", s2.max())

Min après correction: -3.974792574809226
P1 après correction: -3.9414912429049136
Median après correction: 11.080523274274466
P99 après correction: 761.774979083904
Max après correction: 806.6476085434132

In [ ]:
num_cols = [
    "roa",
    "roa_ebit",
    "interest_coverage",
    "debt_ebitda",
    "ebitda_margin",
    "book_leverage",
    "policy_rate_fye",
    "policy_rate_change",
    "leverage_lag",
    "rate_x_leverage_lag",
    "rate_change_x_leverage_lag",
    "size_ln_assets"
]

diagnostics_desc_new = reg[num_cols].describe(
    percentiles=[0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]
).T

diagnostics_desc_new["missing_pct"] = reg[num_cols].isna().mean().values

diagnostics_desc_new.head()

,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,max,missing_pct
roa,781.0,0.083080,0.070410,-0.321651,-0.075651,0.002907,0.041999,0.070569,0.117689,0.203085,0.276664,0.653041,0.000000
roa_ebit,781.0,0.112353,0.071872,-0.057531,-0.057151,0.018704,0.065270,0.098915,0.150459,0.251328,0.323605,0.323701,0.000000
interest_coverage,774.0,37.229878,105.797231,-3.974793,-3.941491,1.665390,6.099205,11.080523,24.203014,107.224085,761.774979,806.647609,0.008963
debt_ebitda,742.0,2.208239,1.991132,0.011371,0.033227,0.232343,0.973946,1.850978,2.870219,4.620355,13.555798,13.625877,0.049936
ebitda_margin,774.0,0.294960,0.211198,0.019581,0.020176,0.071988,0.160796,0.254144,0.364961,0.604591,1.336838,1.353929,0.008963

In [ ]:
output_path = "/content/final_regression_dataset_v2.xlsx"

with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
    reg.to_excel(writer, sheet_name="regression_base", index=False)
    diagnostics_desc_new.to_excel(writer, sheet_name="diagnostics_desc")
    macro.to_excel(writer, sheet_name="macro_zone_rates", index=False)

print("Saved:", output_path)

Saved: /content/final_regression_dataset_v2.xlsx

In [ ]:
from google.colab import files
files.download("/content/final_regression_dataset_v2.xlsx")

In [ ]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

file_path = "/content/final_regression_dataset_v2.xlsx"   # adapte si besoin
df = pd.read_excel(file_path, sheet_name="regression_base")

print(df.shape)
df.head()

(781, 30)

,firm_id,ticker,company_name,country,macro_zone,sector,fiscal_year,roa,roa_ebit,interest_coverage,...,ebit,ebitda,interest_expense,net_income,total_assets,total_debt,source_primary,data_quality_score,notes,interest_coverage_raw_backup
0,F001,AAPL,Apple Inc.,United States,US,Technology,2022,0.282924,0.323701,40.749574,...,1.194370e+11,1.305410e+11,2.931000e+09,9.980300e+10,3.527550e+11,1.118240e+11,Yahoo + SEC override,1.000,NaN,40.749574
1,F001,AAPL,Apple Inc.,United States,US,Technology,2023,0.275098,0.323701,29.062039,...,1.143010e+11,1.258200e+11,3.933000e+09,9.699500e+10,3.525830e+11,1.065720e+11,Yahoo + SEC override,1.000,NaN,29.062039
2,F001,AAPL,Apple Inc.,United States,US,Technology,2024,0.256825,0.323701,NaN,...,1.232160e+11,1.346610e+11,NaN,9.373600e+10,3.649800e+11,9.734100e+10,Yahoo + SEC override,0.875,NaN,NaN
3,F001,AAPL,Apple Inc.,United States,US,Technology,2025,0.306894,0.323701,NaN,...,1.330500e+11,1.447480e+11,NaN,1.120100e+11,3.649800e+11,9.128100e+10,Yahoo + SEC override,0.875,NaN,NaN
4,F002,MSFT,Microsoft Corporation,United States,US,Technology,2022,0.121371,0.145157,20.439599,...,5.295900e+10,1.002390e+11,2.591000e+09,4.428100e+10,3.648400e+11,5.551100e+10,Yahoo + SEC override,1.000,NaN,20.439599

In [ ]:
reg_cols = [
    "firm_id",
    "fiscal_year",
    "country",
    "macro_zone",
    "roa",
    "policy_rate_change",
    "leverage_lag",
    "rate_change_x_leverage_lag",
    "size_ln_assets"
]

reg1 = df[reg_cols].dropna().copy()

print("Observations:", len(reg1))
print("Firmes:", reg1["firm_id"].nunique())
print("Années:", sorted(reg1["fiscal_year"].unique()))
reg1.head()

Observations: 561
Firmes: 191
Années: [np.int64(2023), np.int64(2024), np.int64(2025)]

,firm_id,fiscal_year,country,macro_zone,roa,policy_rate_change,leverage_lag,rate_change_x_leverage_lag,size_ln_assets
1,F001,2023,United States,US,0.275098,1.23,0.317002,0.389912,26.588552
2,F001,2024,United States,US,0.256825,-0.85,0.302261,-0.256922,26.623108
3,F001,2025,United States,US,0.306894,-0.76,0.266702,-0.202694,26.623108
5,F002,2023,United States,US,0.198336,1.23,0.152152,0.187147,26.622725
6,F002,2024,United States,US,0.172086,-0.85,0.152152,-0.129329,26.961909

In [ ]:
print(reg1.describe())

print("\nRépartition par année")
print(reg1["fiscal_year"].value_counts().sort_index())

print("\nRépartition par macro_zone")
print(reg1["macro_zone"].value_counts())

       fiscal_year         roa  policy_rate_change  leverage_lag  \
count   561.000000  561.000000          561.000000    561.000000
mean   2023.987522    0.081260            0.009418      0.275423
std       0.813845    0.067694            1.144878      0.154306
min    2023.000000   -0.121020           -1.546959      0.000000
25%    2023.000000    0.041521           -0.850000      0.168762
50%    2024.000000    0.069138           -0.760000      0.263625
75%    2025.000000    0.112198            1.230000      0.357108
max    2025.000000    0.653041            2.399477      0.845053

       rate_change_x_leverage_lag  size_ln_assets
count                  561.000000      561.000000
mean                    -0.002192       25.185507
std                      0.350404        1.710027
min                     -0.777931       21.666666
25%                     -0.235905       24.148473
50%                     -0.084979       24.898852
75%                      0.227295       25.644523
max                      1.273107       32.170066

Répartition par année
fiscal_year
2023    189
2024    190
2025    182
Name: count, dtype: int64

Répartition par macro_zone
macro_zone
US                254
Euro Area         121
Japan              45
United Kingdom     42
Canada             39
Switzerland        33
Australia          27
Name: count, dtype: int64

In [ ]:
model_pool = smf.ols(
    "roa ~ policy_rate_change + leverage_lag + rate_change_x_leverage_lag + size_ln_assets",
    data=reg1
).fit(cov_type="cluster", cov_kwds={"groups": reg1["firm_id"]})

print(model_pool.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    roa   R-squared:                       0.027
Model:                            OLS   Adj. R-squared:                  0.020
Method:                 Least Squares   F-statistic:                     3.942
Date:                Tue, 31 Mar 2026   Prob (F-statistic):            0.00425
Time:                        13:28:41   Log-Likelihood:                 722.76
No. Observations:                 561   AIC:                            -1436.
Df Residuals:                     556   BIC:                            -1414.
Df Model:                           4
Covariance Type:              cluster
==============================================================================================
                                 coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                      0.2442      0.047      5.231      0.000       0.153       0.336
policy_rate_change            -0.0049      0.004     -1.351      0.177      -0.012       0.002
leverage_lag                  -0.0139      0.027     -0.511      0.609      -0.067       0.039
rate_change_x_leverage_lag     0.0137      0.010      1.362      0.173      -0.006       0.033
size_ln_assets                -0.0063      0.002     -3.534      0.000      -0.010      -0.003
==============================================================================
Omnibus:                      277.678   Durbin-Watson:                   0.897
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3403.652
Skew:                           1.864   Prob(JB):                         0.00
Kurtosis:                      14.477   Cond. No.                         388.
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [ ]:
model_fe = smf.ols(
    "roa ~ policy_rate_change + leverage_lag + rate_change_x_leverage_lag + size_ln_assets + C(firm_id) + C(fiscal_year)",
    data=reg1
).fit(cov_type="cluster", cov_kwds={"groups": reg1["firm_id"]})

print(model_fe.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    roa   R-squared:                       0.800
Model:                            OLS   Adj. R-squared:                  0.692
Method:                 Least Squares   F-statistic:                     1856.
Date:                Tue, 31 Mar 2026   Prob (F-statistic):          9.76e-166
Time:                        13:28:52   Log-Likelihood:                 1166.3
No. Observations:                 561   AIC:                            -1939.
Df Residuals:                     364   BIC:                            -1086.
Df Model:                         196
Covariance Type:              cluster
==============================================================================================
                                 coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                     -0.7780      3.451     -0.225      0.822      -7.542       5.986
C(firm_id)[T.F002]            -0.1022      0.037     -2.795      0.005      -0.174      -0.031
C(firm_id)[T.F003]             0.1900      0.218      0.870      0.384      -0.238       0.618
C(firm_id)[T.F004]            -0.2238      0.080     -2.786      0.005      -0.381      -0.066
C(firm_id)[T.F005]            -0.0861      0.047     -1.828      0.068      -0.178       0.006
C(firm_id)[T.F006]            -0.0868      0.034     -2.530      0.011      -0.154      -0.020
C(firm_id)[T.F007]            -0.1111      0.142     -0.785      0.433      -0.389       0.166
C(firm_id)[T.F008]            -0.1583      0.134     -1.177      0.239      -0.422       0.105
C(firm_id)[T.F009]            -0.1810      0.163     -1.113      0.266      -0.500       0.138
C(firm_id)[T.F010]             0.0176      0.322      0.055      0.956      -0.613       0.649
C(firm_id)[T.F011]            -0.1414      0.146     -0.970      0.332      -0.427       0.144
C(firm_id)[T.F012]            -0.1835      0.124     -1.477      0.140      -0.427       0.060
C(firm_id)[T.F013]            -0.0907      0.368     -0.247      0.805      -0.811       0.630
C(firm_id)[T.F014]            -0.0980      0.321     -0.306      0.760      -0.727       0.531
C(firm_id)[T.F015]            -0.1888      0.209     -0.903      0.367      -0.599       0.221
C(firm_id)[T.F016]            -0.0239      0.308     -0.078      0.938      -0.627       0.579
C(firm_id)[T.F017]            -0.0622      0.248     -0.251      0.802      -0.548       0.423
C(firm_id)[T.F018]             0.0253      0.310      0.082      0.935      -0.582       0.632
C(firm_id)[T.F019]            -0.2003      0.216     -0.926      0.354      -0.624       0.223
C(firm_id)[T.F020]             0.0771      0.417      0.185      0.853      -0.741       0.895
C(firm_id)[T.F021]             0.0950      0.385      0.247      0.805      -0.659       0.849
C(firm_id)[T.F022]            -0.0912      0.390     -0.234      0.815      -0.855       0.673
C(firm_id)[T.F023]             0.0705      0.455      0.155      0.877      -0.820       0.961
C(firm_id)[T.F024]            -0.2863      0.076     -3.752      0.000      -0.436      -0.137
C(firm_id)[T.F025]            -0.2703      0.113     -2.392      0.017      -0.492      -0.049
C(firm_id)[T.F026]            -0.1526      0.184     -0.830      0.407      -0.513       0.208
C(firm_id)[T.F027]            -0.0868      0.192     -0.452      0.651      -0.463       0.290
C(firm_id)[T.F028]            -0.1136      0.088     -1.287      0.198      -0.287       0.059
C(firm_id)[T.F029]            -0.2048      0.131     -1.567      0.117      -0.461       0.051
C(firm_id)[T.F030]            -0.1406      0.144     -0.978      0.328      -0.422       0.141
C(firm_id)[T.F031]            -0.2311      0.066     -3.505      0.000      -0.360      -0.102
C(firm_id)[T.F032]            -0.1662      0.165     -1.005      0.315      -0.490       0.158
C(firm_id)[T.F033]            -0.1155      0.195     -0.593      0.553      -0.497       0.266
C(firm_id)[T.F034]            -0.1718      0.192     -0.893      0.372      -0.549       0.205
C(firm_id)[T.F036]            -0.1386      0.289     -0.480      0.631      -0.704       0.427
C(firm_id)[T.F037]            -0.1588      0.276     -0.576      0.565      -0.699       0.382
C(firm_id)[T.F038]            -0.0509      0.315     -0.162      0.871      -0.668       0.566
C(firm_id)[T.F039]             0.0221      0.421      0.052      0.958      -0.802       0.846
C(firm_id)[T.F040]            -0.2135      0.027     -8.007      0.000      -0.266      -0.161
C(firm_id)[T.F041]            -0.2037      0.175     -1.161      0.246      -0.547       0.140
C(firm_id)[T.F042]            -0.0773      0.294     -0.263      0.793      -0.654       0.499
C(firm_id)[T.F043]            -0.2468      0.046     -5.361      0.000      -0.337      -0.157
C(firm_id)[T.F044]            -0.0832      0.246     -0.339      0.735      -0.565       0.398
C(firm_id)[T.F045]            -0.2149      0.109     -1.979      0.048      -0.428      -0.002
C(firm_id)[T.F046]            -0.0458      0.251     -0.182      0.855      -0.537       0.446
C(firm_id)[T.F047]            -0.2236      0.076     -2.925      0.003      -0.373      -0.074
C(firm_id)[T.F048]            -0.2035      0.040     -5.082      0.000      -0.282      -0.125
C(firm_id)[T.F049]            -0.2087      0.070     -2.960      0.003      -0.347      -0.070
C(firm_id)[T.F050]            -0.2410      0.011    -22.669      0.000      -0.262      -0.220
C(firm_id)[T.F051]            -0.0647      0.258     -0.251      0.802      -0.570       0.441
C(firm_id)[T.F052]             0.0203      0.342      0.060      0.953      -0.650       0.691
C(firm_id)[T.F053]            -0.0131      0.367     -0.036      0.971      -0.732       0.706
C(firm_id)[T.F054]            -0.0893      0.433     -0.206      0.836      -0.937       0.758
C(firm_id)[T.F055]            -0.0708      0.325     -0.218      0.828      -0.708       0.566
C(firm_id)[T.F056]            -0.0678      0.293     -0.232      0.817      -0.641       0.506
C(firm_id)[T.F057]            -0.0362      0.279     -0.130      0.897      -0.582       0.510
C(firm_id)[T.F058]            -0.0307      0.194     -0.158      0.875      -0.412       0.350
C(firm_id)[T.F059]            -0.0371      0.325     -0.114      0.909      -0.674       0.600
C(firm_id)[T.F060]             0.0427      0.481      0.089      0.929      -0.901       0.986
C(firm_id)[T.F061]            -0.1978      0.049     -4.072      0.000      -0.293      -0.103
C(firm_id)[T.F062]            -0.1429      0.242     -0.591      0.555      -0.617       0.331
C(firm_id)[T.F063]            -0.1121      0.141     -0.798      0.425      -0.388       0.163
C(firm_id)[T.F064]            -0.1104      0.170     -0.650      0.516      -0.443       0.222
C(firm_id)[T.F065]            -0.1348      0.170     -0.793      0.428      -0.468       0.198
C(firm_id)[T.F066]            -0.0706      0.233     -0.303      0.762      -0.527       0.386
C(firm_id)[T.F067]            -0.1692      0.247     -0.684      0.494      -0.654       0.316
C(firm_id)[T.F068]             0.0068      0.407      0.017      0.987      -0.792       0.805
C(firm_id)[T.F069]            -0.1131      0.180     -0.627      0.531      -0.467       0.241
C(firm_id)[T.F070]            -0.1549      0.166     -0.934      0.351      -0.480       0.170
C(firm_id)[T.F071]            -0.1362      0.213     -0.638      0.523      -0.555       0.282
C(firm_id)[T.F072]            -0.1403      0.241     -0.581      0.561      -0.614       0.333
C(firm_id)[T.F073]            -0.2181      0.101     -2.164      0.030      -0.416      -0.021
C(firm_id)[T.F074]            -0.0999      0.244     -0.410      0.682      -0.577       0.377
C(firm_id)[T.F075]            -0.2703      0.113     -2.392      0.017      -0.492      -0.049
C(firm_id)[T.F076]            -0.1309      0.211     -0.622      0.534      -0.544       0.282
C(firm_id)[T.F077]            -0.1730      0.187     -0.924      0.356      -0.540       0.194
C(firm_id)[T.F078]            -0.1111      0.220     -0.504      0.614      -0.543       0.321
C(firm_id)[T.F079]            -0.1142      0.279     -0.409      0.683      -0.662       0.434
C(firm_id)[T.F080]            -0.0989      0.289     -0.342      0.732      -0.665       0.467
C(firm_id)[T.F081]            -0.0834      0.327     -0.255      0.799      -0.724       0.557
C(firm_id)[T.F082]            -0.0438      0.375     -0.117      0.907      -0.779       0.692
C(firm_id)[T.F083]            -0.1443      0.416     -0.347      0.728      -0.959       0.670
C(firm_id)[T.F084]            -0.0878      0.360     -0.244      0.807      -0.793       0.617
C(firm_id)[T.F085]            -0.1284      0.394     -0.325      0.745      -0.902       0.645
C(firm_id)[T.F086]            -0.1428      0.193     -0.741      0.459      -0.521       0.235
C(firm_id)[T.F087]            -0.1339      0.297     -0.451      0.652      -0.716       0.448
C(firm_id)[T.F088]            -0.1325      0.243     -0.544      0.586      -0.610       0.345
C(firm_id)[T.F089]            -0.2088      0.031     -6.800      0.000      -0.269      -0.149
C(firm_id)[T.F090]            -0.2104      0.037     -5.623      0.000      -0.284      -0.137
C(firm_id)[T.F091]            -0.4506      0.710     -0.635      0.526      -1.841       0.940
C(firm_id)[T.F092]            -0.4326      0.592     -0.731      0.465      -1.593       0.728
C(firm_id)[T.F093]            -0.2723      0.300     -0.906      0.365      -0.861       0.317
C(firm_id)[T.F095]            -0.2756      0.351     -0.785      0.432      -0.964       0.413
C(firm_id)[T.F096]            -0.3753      0.465     -0.808      0.419      -1.286       0.535
C(firm_id)[T.F098]            -0.4118      0.566     -0.728      0.467      -1.521       0.697
C(firm_id)[T.F099]            -0.2477      0.274     -0.903      0.366      -0.785       0.290
C(firm_id)[T.F102]            -0.2864      0.208     -1.380      0.168      -0.693       0.120
C(firm_id)[T.F104]            -0.3075      0.284     -1.082      0.279      -0.865       0.250
C(firm_id)[T.F105]            -0.1713      0.157     -1.094      0.274      -0.478       0.136
C(firm_id)[T.F106]            -0.3647      0.409     -0.892      0.372      -1.166       0.436
C(firm_id)[T.F107]            -0.4264      0.570     -0.748      0.454      -1.543       0.691
C(firm_id)[T.F108]            -0.3296      0.336     -0.980      0.327      -0.989       0.330
C(firm_id)[T.F109]            -0.3811      0.479     -0.795      0.427      -1.321       0.558
C(firm_id)[T.F110]            -0.3684      0.477     -0.772      0.440      -1.304       0.567
C(firm_id)[T.F111]            -0.2390      0.014    -17.542      0.000      -0.266      -0.212
C(firm_id)[T.F112]            -0.1600      0.161     -0.996      0.319      -0.475       0.155
C(firm_id)[T.F113]            -0.1192      0.207     -0.575      0.565      -0.525       0.287
C(firm_id)[T.F114]            -0.0281      0.416     -0.068      0.946      -0.843       0.787
C(firm_id)[T.F115]            -0.2526      0.033     -7.543      0.000      -0.318      -0.187
C(firm_id)[T.F116]            -0.1356      0.236     -0.575      0.565      -0.598       0.327
C(firm_id)[T.F117]            -0.1188      0.271     -0.438      0.661      -0.651       0.413
C(firm_id)[T.F118]            -0.2428      0.150     -1.622      0.105      -0.536       0.051
C(firm_id)[T.F119]            -0.1165      0.341     -0.342      0.732      -0.785       0.552
C(firm_id)[T.F120]            -0.1401      0.153     -0.915      0.360      -0.440       0.160
C(firm_id)[T.F121]            -0.2330      0.132     -1.763      0.078      -0.492       0.026
C(firm_id)[T.F122]            -0.2475      0.229     -1.080      0.280      -0.697       0.202
C(firm_id)[T.F123]            -0.2247      0.125     -1.791      0.073      -0.471       0.021
C(firm_id)[T.F124]            -0.1626      0.340     -0.478      0.633      -0.830       0.505
C(firm_id)[T.F125]            -0.1060      0.353     -0.300      0.764      -0.799       0.586
C(firm_id)[T.F126]            -0.1008      0.304     -0.332      0.740      -0.696       0.495
C(firm_id)[T.F127]            -0.1138      0.241     -0.472      0.637      -0.586       0.358
C(firm_id)[T.F128]            -0.1740      0.187     -0.931      0.352      -0.540       0.192
C(firm_id)[T.F129]            -0.1713      0.205     -0.834      0.404      -0.574       0.231
C(firm_id)[T.F130]            -0.0460      0.385     -0.119      0.905      -0.801       0.709
C(firm_id)[T.F131]            -0.1235      0.187     -0.662      0.508      -0.489       0.242
C(firm_id)[T.F132]            -0.1498      0.179     -0.837      0.402      -0.500       0.201
C(firm_id)[T.F133]            -0.0721      0.426     -0.169      0.866      -0.907       0.763
C(firm_id)[T.F134]            -0.0980      0.430     -0.228      0.820      -0.941       0.744
C(firm_id)[T.F135]            -0.1456      0.259     -0.563      0.574      -0.653       0.362
C(firm_id)[T.F136]            -0.0989      0.316     -0.313      0.754      -0.719       0.521
C(firm_id)[T.F138]            -0.1277      0.459     -0.278      0.781      -1.028       0.772
C(firm_id)[T.F140]            -0.1834      0.239     -0.768      0.443      -0.652       0.285
C(firm_id)[T.F141]            -0.1555      0.119     -1.303      0.193      -0.389       0.078
C(firm_id)[T.F142]             0.0258      0.360      0.072      0.943      -0.679       0.731
C(firm_id)[T.F143]            -0.0978      0.240     -0.407      0.684      -0.569       0.373
C(firm_id)[T.F144]            -0.2076      0.135     -1.541      0.123      -0.472       0.056
C(firm_id)[T.F145]            -0.2063      0.030     -6.926      0.000      -0.265      -0.148
C(firm_id)[T.F146]            -0.1930      0.134     -1.441      0.150      -0.455       0.069
C(firm_id)[T.F147]            -0.1448      0.228     -0.635      0.526      -0.592       0.302
C(firm_id)[T.F148]            -0.1379      0.256     -0.538      0.590      -0.640       0.364
C(firm_id)[T.F149]            -0.1144      0.341     -0.335      0.738      -0.784       0.555
C(firm_id)[T.F150]            -0.2010      0.137     -1.469      0.142      -0.469       0.067
C(firm_id)[T.F151]            -0.1584      0.288     -0.550      0.582      -0.723       0.406
C(firm_id)[T.F152]            -0.1427      0.295     -0.484      0.628      -0.720       0.435
C(firm_id)[T.F153]            -0.1939      0.242     -0.801      0.423      -0.668       0.281
C(firm_id)[T.F154]            -0.1942      0.229     -0.850      0.395      -0.642       0.254
C(firm_id)[T.F155]            -0.2560      0.146     -1.758      0.079      -0.541       0.029
C(firm_id)[T.F156]            -0.1402      0.211     -0.663      0.507      -0.554       0.274
C(firm_id)[T.F157]            -0.1893      0.114     -1.668      0.095      -0.412       0.033
C(firm_id)[T.F158]            -0.2341      0.043     -5.456      0.000      -0.318      -0.150
C(firm_id)[T.F159]            -0.2290      0.044     -5.226      0.000      -0.315      -0.143
C(firm_id)[T.F160]            -0.2829      0.070     -4.015      0.000      -0.421      -0.145
C(firm_id)[T.F161]            -0.2058      0.200     -1.029      0.303      -0.598       0.186
C(firm_id)[T.F162]            -0.2595      0.156     -1.663      0.096      -0.565       0.046
C(firm_id)[T.F163]            -0.1190      0.327     -0.363      0.716      -0.761       0.523
C(firm_id)[T.F164]            -0.2257      0.035     -6.474      0.000      -0.294      -0.157
C(firm_id)[T.F165]            -0.1620      0.216     -0.750      0.453      -0.585       0.261
C(firm_id)[T.F166]            -0.1314      0.381     -0.345      0.730      -0.877       0.615
C(firm_id)[T.F167]            -0.0845      0.432     -0.195      0.845      -0.932       0.763
C(firm_id)[T.F168]            -0.1074      0.421     -0.255      0.799      -0.932       0.717
C(firm_id)[T.F169]            -0.1634      0.262     -0.624      0.533      -0.676       0.350
C(firm_id)[T.F170]            -0.1459      0.255     -0.572      0.567      -0.645       0.354
C(firm_id)[T.F171]            -0.1593      0.137     -1.164      0.245      -0.428       0.109
C(firm_id)[T.F172]            -0.1161      0.173     -0.671      0.502      -0.455       0.223
C(firm_id)[T.F173]            -0.1012      0.163     -0.621      0.535      -0.421       0.218
C(firm_id)[T.F174]            -0.0983      0.281     -0.350      0.726      -0.648       0.452
C(firm_id)[T.F175]            -0.1233      0.387     -0.318      0.750      -0.882       0.636
C(firm_id)[T.F176]            -0.0818      0.414     -0.197      0.843      -0.893       0.730
C(firm_id)[T.F177]            -0.0558      0.451     -0.124      0.902      -0.940       0.828
C(firm_id)[T.F178]            -0.0313      0.270     -0.116      0.908      -0.561       0.498
C(firm_id)[T.F179]            -0.1526      0.321     -0.475      0.635      -0.782       0.477
C(firm_id)[T.F180]            -0.0119      0.541     -0.022      0.982      -1.072       1.048
C(firm_id)[T.F181]            -0.0207      0.267     -0.077      0.938      -0.543       0.502
C(firm_id)[T.F182]            -0.0691      0.221     -0.313      0.754      -0.502       0.363
C(firm_id)[T.F183]            -0.0654      0.452     -0.145      0.885      -0.951       0.820
C(firm_id)[T.F184]            -0.1600      0.261     -0.613      0.540      -0.671       0.351
C(firm_id)[T.F185]             0.0354      0.558      0.063      0.949      -1.058       1.128
C(firm_id)[T.F186]            -0.1726      0.248     -0.695      0.487      -0.659       0.314
C(firm_id)[T.F187]            -0.0126      0.478     -0.026      0.979      -0.949       0.924
C(firm_id)[T.F188]            -0.1819      0.331     -0.549      0.583      -0.831       0.467
C(firm_id)[T.F189]            -0.0474      0.571     -0.083      0.934      -1.166       1.071
C(firm_id)[T.F190]            -0.0460      0.411     -0.112      0.911      -0.852       0.760
C(firm_id)[T.F191]            -0.1364      0.162     -0.843      0.399      -0.453       0.181
C(firm_id)[T.F192]            -0.1213      0.296     -0.411      0.681      -0.701       0.458
C(firm_id)[T.F193]            -0.1566      0.313     -0.500      0.617      -0.771       0.457
C(firm_id)[T.F194]            -0.0786      0.340     -0.231      0.817      -0.745       0.588
C(firm_id)[T.F195]            -0.1686      0.231     -0.731      0.465      -0.621       0.284
C(firm_id)[T.F196]            -0.1048      0.385     -0.272      0.786      -0.859       0.650
C(firm_id)[T.F197]            -0.1544      0.273     -0.566      0.571      -0.689       0.380
C(firm_id)[T.F198]            -0.0013      0.461     -0.003      0.998      -0.905       0.902
C(firm_id)[T.F199]             0.0395      0.635      0.062      0.950      -1.206       1.285
C(fiscal_year)[T.2024]         0.0006      0.017      0.036      0.971      -0.033       0.034
C(fiscal_year)[T.2025]         0.0077      0.023      0.329      0.742      -0.038       0.054
policy_rate_change          8.134e-06      0.004      0.002      0.998      -0.008       0.008
leverage_lag                  -0.0172      0.097     -0.177      0.859      -0.207       0.173
rate_change_x_leverage_lag     0.0102      0.014      0.737      0.461      -0.017       0.037
size_ln_assets                 0.0398      0.130      0.306      0.760      -0.216       0.295
==============================================================================
Omnibus:                      172.899   Durbin-Watson:                   2.427
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            14424.096

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 196, but rank is 6
  warnings.warn('covariance of constraints does not have full '

In [ ]:
main_vars = [
    "policy_rate_change",
    "leverage_lag",
    "rate_change_x_leverage_lag",
    "size_ln_assets"
]

results_main = pd.DataFrame({
    "coef": model_fe.params[main_vars],
    "std_err": model_fe.bse[main_vars],
    "t_stat": model_fe.tvalues[main_vars],
    "p_value": model_fe.pvalues[main_vars]
})

print(results_main)

                                coef   std_err    t_stat   p_value
policy_rate_change          0.000008  0.004009  0.002029  0.998381
leverage_lag               -0.017183  0.096941 -0.177253  0.859309
rate_change_x_leverage_lag  0.010151  0.013774  0.736995  0.461125
size_ln_assets              0.039839  0.130286  0.305779  0.759773

In [ ]:
print("N observations :", int(model_fe.nobs))
print("R² :", round(model_fe.rsquared, 4))
print("Adj. R² :", round(model_fe.rsquared_adj, 4))

print("\nCoefficient clé :")
print("rate_change_x_leverage_lag =", round(model_fe.params["rate_change_x_leverage_lag"], 6))
print("p-value =", round(model_fe.pvalues["rate_change_x_leverage_lag"], 6))

N observations : 561
R² : 0.7998
Adj. R² : 0.692

Coefficient clé :
rate_change_x_leverage_lag = 0.010151
p-value = 0.461125

In [ ]:
import pandas as pd
import statsmodels.formula.api as smf

file_path = "/content/final_regression_dataset_v2.xlsx"   # adapte si besoin
df = pd.read_excel(file_path, sheet_name="regression_base")

reg_cols = [
    "firm_id",
    "fiscal_year",
    "roa_ebit",
    "policy_rate_change",
    "leverage_lag",
    "rate_change_x_leverage_lag",
    "size_ln_assets"
]

reg2 = df[reg_cols].dropna().copy()

print("Observations:", len(reg2))
print("Firmes:", reg2["firm_id"].nunique())
print("Années:", sorted(reg2["fiscal_year"].unique()))

model_roa_ebit = smf.ols(
    "roa_ebit ~ policy_rate_change + leverage_lag + rate_change_x_leverage_lag + size_ln_assets + C(firm_id) + C(fiscal_year)",
    data=reg2
).fit(cov_type="cluster", cov_kwds={"groups": reg2["firm_id"]})

print(model_roa_ebit.summary())

Observations: 561
Firmes: 191
Années: [np.int64(2023), np.int64(2024), np.int64(2025)]

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 196, but rank is 6
  warnings.warn('covariance of constraints does not have full '

                            OLS Regression Results
==============================================================================
Dep. Variable:               roa_ebit   R-squared:                       0.874
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     2179.
Date:                Tue, 31 Mar 2026   Prob (F-statistic):          3.11e-172
Time:                        13:41:53   Log-Likelihood:                 1278.1
No. Observations:                 561   AIC:                            -2162.
Df Residuals:                     364   BIC:                            -1309.
Df Model:                         196
Covariance Type:              cluster
==============================================================================================
                                 coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                     -0.1513      1.463     -0.103      0.918      -3.020       2.717
C(firm_id)[T.F002]            -0.0864      0.017     -4.983      0.000      -0.120      -0.052
C(firm_id)[T.F003]            -0.0421      0.094     -0.450      0.653      -0.225       0.141
C(firm_id)[T.F004]            -0.2351      0.034     -6.975      0.000      -0.301      -0.169
C(firm_id)[T.F005]            -0.0939      0.025     -3.804      0.000      -0.142      -0.046
C(firm_id)[T.F006]            -0.0841      0.023     -3.703      0.000      -0.129      -0.040
C(firm_id)[T.F007]            -0.1607      0.059     -2.744      0.006      -0.276      -0.046
C(firm_id)[T.F008]            -0.2096      0.057     -3.649      0.000      -0.322      -0.097
C(firm_id)[T.F009]            -0.2361      0.073     -3.237      0.001      -0.379      -0.093
C(firm_id)[T.F010]            -0.0308      0.138     -0.223      0.824      -0.302       0.241
C(firm_id)[T.F011]            -0.1841      0.065     -2.811      0.005      -0.312      -0.056
C(firm_id)[T.F012]            -0.2408      0.051     -4.691      0.000      -0.341      -0.140
C(firm_id)[T.F013]            -0.2057      0.159     -1.292      0.196      -0.518       0.106
C(firm_id)[T.F014]            -0.1735      0.137     -1.270      0.204      -0.441       0.094
C(firm_id)[T.F015]            -0.2592      0.094     -2.755      0.006      -0.444      -0.075
C(firm_id)[T.F016]            -0.0995      0.129     -0.770      0.441      -0.353       0.154
C(firm_id)[T.F017]            -0.1033      0.105     -0.983      0.326      -0.309       0.103
C(firm_id)[T.F018]            -0.0391      0.133     -0.295      0.768      -0.299       0.221
C(firm_id)[T.F019]            -0.2553      0.094     -2.726      0.006      -0.439      -0.072
C(firm_id)[T.F020]             0.0047      0.174      0.027      0.978      -0.337       0.347
C(firm_id)[T.F021]             0.0207      0.163      0.127      0.899      -0.299       0.340
C(firm_id)[T.F022]            -0.2276      0.167     -1.363      0.173      -0.555       0.100
C(firm_id)[T.F023]            -0.0169      0.197     -0.086      0.932      -0.403       0.369
C(firm_id)[T.F024]            -0.3337      0.033    -10.087      0.000      -0.399      -0.269
C(firm_id)[T.F025]            -0.3245      0.047     -6.927      0.000      -0.416      -0.233
C(firm_id)[T.F026]            -0.2247      0.076     -2.943      0.003      -0.374      -0.075
C(firm_id)[T.F027]            -0.0848      0.081     -1.052      0.293      -0.243       0.073
C(firm_id)[T.F028]            -0.1875      0.040     -4.685      0.000      -0.266      -0.109
C(firm_id)[T.F029]            -0.2192      0.054     -4.060      0.000      -0.325      -0.113
C(firm_id)[T.F030]            -0.1800      0.061     -2.975      0.003      -0.299      -0.061
C(firm_id)[T.F031]            -0.2737      0.029     -9.570      0.000      -0.330      -0.218
C(firm_id)[T.F032]            -0.2318      0.069     -3.350      0.001      -0.367      -0.096
C(firm_id)[T.F033]            -0.2060      0.084     -2.453      0.014      -0.371      -0.041
C(firm_id)[T.F034]            -0.2351      0.083     -2.846      0.004      -0.397      -0.073
C(firm_id)[T.F036]            -0.2128      0.122     -1.741      0.082      -0.452       0.027
C(firm_id)[T.F037]            -0.1920      0.117     -1.647      0.100      -0.420       0.037
C(firm_id)[T.F038]            -0.1054      0.130     -0.810      0.418      -0.360       0.150
C(firm_id)[T.F039]            -0.0455      0.175     -0.259      0.795      -0.389       0.298
C(firm_id)[T.F040]            -0.2215      0.013    -16.834      0.000      -0.247      -0.196
C(firm_id)[T.F041]            -0.2396      0.075     -3.181      0.001      -0.387      -0.092
C(firm_id)[T.F042]            -0.1706      0.129     -1.323      0.186      -0.423       0.082
C(firm_id)[T.F043]            -0.2793      0.021    -13.407      0.000      -0.320      -0.238
C(firm_id)[T.F044]            -0.1243      0.102     -1.221      0.222      -0.324       0.075
C(firm_id)[T.F045]            -0.2471      0.048     -5.142      0.000      -0.341      -0.153
C(firm_id)[T.F046]            -0.0979      0.106     -0.924      0.355      -0.306       0.110
C(firm_id)[T.F047]            -0.2610      0.033     -7.874      0.000      -0.326      -0.196
C(firm_id)[T.F048]            -0.2368      0.017    -14.305      0.000      -0.269      -0.204
C(firm_id)[T.F049]            -0.2367      0.029     -8.130      0.000      -0.294      -0.180
C(firm_id)[T.F050]            -0.2579      0.006    -40.078      0.000      -0.270      -0.245
C(firm_id)[T.F051]            -0.2301      0.110     -2.095      0.036      -0.445      -0.015
C(firm_id)[T.F052]            -0.0160      0.142     -0.113      0.910      -0.293       0.261
C(firm_id)[T.F053]            -0.1648      0.158     -1.041      0.298      -0.475       0.146
C(firm_id)[T.F054]            -0.1873      0.183     -1.026      0.305      -0.545       0.171
C(firm_id)[T.F055]            -0.1337      0.135     -0.992      0.321      -0.398       0.130
C(firm_id)[T.F056]            -0.1423      0.125     -1.142      0.253      -0.386       0.102
C(firm_id)[T.F057]            -0.0729      0.116     -0.630      0.528      -0.299       0.154
C(firm_id)[T.F058]            -0.0432      0.080     -0.538      0.591      -0.201       0.114
C(firm_id)[T.F059]            -0.0770      0.141     -0.547      0.584      -0.353       0.199
C(firm_id)[T.F060]            -0.0278      0.204     -0.137      0.891      -0.427       0.371
C(firm_id)[T.F061]            -0.2052      0.024     -8.386      0.000      -0.253      -0.157
C(firm_id)[T.F062]            -0.2021      0.103     -1.964      0.050      -0.404      -0.000
C(firm_id)[T.F063]            -0.1462      0.060     -2.419      0.016      -0.265      -0.028
C(firm_id)[T.F064]            -0.1874      0.070     -2.658      0.008      -0.325      -0.049
C(firm_id)[T.F065]            -0.1833      0.070     -2.604      0.009      -0.321      -0.045
C(firm_id)[T.F066]            -0.0986      0.097     -1.019      0.308      -0.288       0.091
C(firm_id)[T.F067]            -0.2302      0.106     -2.182      0.029      -0.437      -0.023
C(firm_id)[T.F068]            -0.0404      0.170     -0.238      0.812      -0.373       0.292
C(firm_id)[T.F069]            -0.1653      0.075     -2.193      0.028      -0.313      -0.018
C(firm_id)[T.F070]            -0.2139      0.069     -3.106      0.002      -0.349      -0.079
C(firm_id)[T.F071]            -0.1826      0.090     -2.023      0.043      -0.360      -0.006
C(firm_id)[T.F072]            -0.2018      0.104     -1.938      0.053      -0.406       0.002
C(firm_id)[T.F073]            -0.2687      0.044     -6.177      0.000      -0.354      -0.183
C(firm_id)[T.F074]            -0.1537      0.102     -1.507      0.132      -0.354       0.046
C(firm_id)[T.F075]            -0.3245      0.047     -6.927      0.000      -0.416      -0.233
C(firm_id)[T.F076]            -0.1749      0.089     -1.956      0.050      -0.350       0.000
C(firm_id)[T.F077]            -0.2317      0.078     -2.987      0.003      -0.384      -0.080
C(firm_id)[T.F078]            -0.1612      0.091     -1.767      0.077      -0.340       0.018
C(firm_id)[T.F079]            -0.1724      0.116     -1.480      0.139      -0.401       0.056
C(firm_id)[T.F080]            -0.1664      0.123     -1.355      0.176      -0.407       0.074
C(firm_id)[T.F081]            -0.1488      0.137     -1.082      0.279      -0.418       0.121
C(firm_id)[T.F082]            -0.1063      0.159     -0.668      0.504      -0.418       0.206
C(firm_id)[T.F083]            -0.0935      0.178     -0.526      0.599      -0.442       0.255
C(firm_id)[T.F084]            -0.1688      0.151     -1.116      0.265      -0.465       0.128
C(firm_id)[T.F085]            -0.2162      0.167     -1.296      0.195      -0.543       0.111
C(firm_id)[T.F086]            -0.1885      0.082     -2.303      0.021      -0.349      -0.028
C(firm_id)[T.F087]            -0.2281      0.125     -1.823      0.068      -0.473       0.017
C(firm_id)[T.F088]            -0.1688      0.105     -1.609      0.108      -0.374       0.037
C(firm_id)[T.F089]            -0.2043      0.017    -11.681      0.000      -0.239      -0.170
C(firm_id)[T.F090]            -0.2148      0.025     -8.717      0.000      -0.263      -0.166
C(firm_id)[T.F091]            -0.3570      0.302     -1.184      0.236      -0.948       0.234
C(firm_id)[T.F092]            -0.3543      0.248     -1.429      0.153      -0.840       0.132
C(firm_id)[T.F093]            -0.2023      0.125     -1.615      0.106      -0.448       0.043
C(firm_id)[T.F095]            -0.1972      0.146     -1.354      0.176      -0.483       0.088
C(firm_id)[T.F096]            -0.3073      0.195     -1.578      0.115      -0.689       0.074
C(firm_id)[T.F098]            -0.3340      0.240     -1.391      0.164      -0.805       0.137
C(firm_id)[T.F099]            -0.1943      0.114     -1.706      0.088      -0.418       0.029
C(firm_id)[T.F102]            -0.2648      0.086     -3.071      0.002      -0.434      -0.096
C(firm_id)[T.F104]            -0.2747      0.118     -2.331      0.020      -0.506      -0.044
C(firm_id)[T.F105]            -0.1261      0.065     -1.937      0.053      -0.254       0.001
C(firm_id)[T.F106]            -0.3081      0.171     -1.805      0.071      -0.643       0.026
C(firm_id)[T.F107]            -0.3467      0.239     -1.452      0.147      -0.815       0.121
C(firm_id)[T.F108]            -0.2781      0.141     -1.971      0.049      -0.555      -0.002
C(firm_id)[T.F109]            -0.3059      0.201     -1.522      0.128      -0.700       0.088
C(firm_id)[T.F110]            -0.3032      0.202     -1.501      0.133      -0.699       0.093
C(firm_id)[T.F111]            -0.2298      0.008    -27.699      0.000      -0.246      -0.214
C(firm_id)[T.F112]            -0.2009      0.068     -2.962      0.003      -0.334      -0.068
C(firm_id)[T.F113]            -0.1723      0.086     -1.993      0.046      -0.342      -0.003
C(firm_id)[T.F114]            -0.0928      0.174     -0.533      0.594      -0.434       0.248
C(firm_id)[T.F115]            -0.2548      0.016    -16.198      0.000      -0.286      -0.224
C(firm_id)[T.F116]            -0.1889      0.099     -1.900      0.057      -0.384       0.006
C(firm_id)[T.F117]            -0.1667      0.113     -1.480      0.139      -0.387       0.054
C(firm_id)[T.F118]            -0.2729      0.063     -4.337      0.000      -0.396      -0.150
C(firm_id)[T.F119]            -0.1781      0.144     -1.239      0.215      -0.460       0.104
C(firm_id)[T.F120]            -0.1479      0.068     -2.181      0.029      -0.281      -0.015
C(firm_id)[T.F121]            -0.2705      0.056     -4.808      0.000      -0.381      -0.160
C(firm_id)[T.F122]            -0.2610      0.097     -2.681      0.007      -0.452      -0.070
C(firm_id)[T.F123]            -0.2684      0.052     -5.175      0.000      -0.370      -0.167
C(firm_id)[T.F124]            -0.2322      0.144     -1.609      0.108      -0.515       0.051
C(firm_id)[T.F125]            -0.1698      0.150     -1.133      0.257      -0.464       0.124
C(firm_id)[T.F126]            -0.1639      0.128     -1.284      0.199      -0.414       0.086
C(firm_id)[T.F127]            -0.1654      0.101     -1.637      0.102      -0.363       0.033
C(firm_id)[T.F128]            -0.2604      0.079     -3.278      0.001      -0.416      -0.105
C(firm_id)[T.F129]            -0.2267      0.085     -2.674      0.007      -0.393      -0.061
C(firm_id)[T.F130]            -0.1494      0.165     -0.907      0.365      -0.472       0.173
C(firm_id)[T.F131]            -0.1613      0.081     -1.980      0.048      -0.321      -0.002
C(firm_id)[T.F132]            -0.1872      0.078     -2.395      0.017      -0.340      -0.034
C(firm_id)[T.F133]            -0.1860      0.184     -1.012      0.311      -0.546       0.174
C(firm_id)[T.F134]            -0.1952      0.181     -1.077      0.281      -0.550       0.160
C(firm_id)[T.F135]            -0.1654      0.113     -1.462      0.144      -0.387       0.056
C(firm_id)[T.F136]            -0.1478      0.139     -1.066      0.286      -0.420       0.124
C(firm_id)[T.F138]            -0.2338      0.194     -1.206      0.228      -0.614       0.146
C(firm_id)[T.F140]            -0.2512      0.099     -2.541      0.011      -0.445      -0.057
C(firm_id)[T.F141]            -0.1696      0.051     -3.345      0.001      -0.269      -0.070
C(firm_id)[T.F142]             0.0063      0.155      0.040      0.968      -0.298       0.311
C(firm_id)[T.F143]            -0.1329      0.104     -1.277      0.202      -0.337       0.071
C(firm_id)[T.F144]            -0.2487      0.061     -4.054      0.000      -0.369      -0.128
C(firm_id)[T.F145]            -0.1961      0.016    -12.036      0.000      -0.228      -0.164
C(firm_id)[T.F146]            -0.2462      0.059     -4.138      0.000      -0.363      -0.130
C(firm_id)[T.F147]            -0.1880      0.098     -1.927      0.054      -0.379       0.003
C(firm_id)[T.F148]            -0.1981      0.109     -1.820      0.069      -0.411       0.015
C(firm_id)[T.F149]            -0.1844      0.145     -1.274      0.203      -0.468       0.099
C(firm_id)[T.F150]            -0.2358      0.058     -4.063      0.000      -0.350      -0.122
C(firm_id)[T.F151]            -0.2366      0.123     -1.920      0.055      -0.478       0.005
C(firm_id)[T.F152]            -0.2092      0.124     -1.688      0.091      -0.452       0.034
C(firm_id)[T.F153]            -0.2494      0.105     -2.369      0.018      -0.456      -0.043
C(firm_id)[T.F154]            -0.2365      0.097     -2.432      0.015      -0.427      -0.046
C(firm_id)[T.F155]            -0.3204      0.060     -5.313      0.000      -0.439      -0.202
C(firm_id)[T.F156]            -0.1868      0.092     -2.033      0.042      -0.367      -0.007
C(firm_id)[T.F157]            -0.2275      0.047     -4.789      0.000      -0.321      -0.134
C(firm_id)[T.F158]            -0.2669      0.018    -14.841      0.000      -0.302      -0.232
C(firm_id)[T.F159]            -0.2662      0.018    -14.754      0.000      -0.302      -0.231
C(firm_id)[T.F160]            -0.3024      0.030    -10.003      0.000      -0.362      -0.243
C(firm_id)[T.F161]            -0.2589      0.085     -3.058      0.002      -0.425      -0.093
C(firm_id)[T.F162]            -0.3069      0.065     -4.719      0.000      -0.434      -0.179
C(firm_id)[T.F163]            -0.1849      0.140     -1.321      0.186      -0.459       0.089
C(firm_id)[T.F164]            -0.2434      0.018    -13.692      0.000      -0.278      -0.209
C(firm_id)[T.F165]            -0.2023      0.091     -2.222      0.026      -0.381      -0.024
C(firm_id)[T.F166]            -0.2147      0.161     -1.336      0.182      -0.530       0.100
C(firm_id)[T.F167]            -0.1540      0.188     -0.820      0.412      -0.522       0.214
C(firm_id)[T.F168]            -0.1720      0.180     -0.955      0.339      -0.525       0.181
C(firm_id)[T.F169]            -0.2162      0.116     -1.865      0.062      -0.443       0.011
C(firm_id)[T.F170]            -0.2074      0.109     -1.903      0.057      -0.421       0.006
C(firm_id)[T.F171]            -0.2057      0.057     -3.638      0.000      -0.317      -0.095
C(firm_id)[T.F172]            -0.1438      0.072     -1.987      0.047      -0.286      -0.002
C(firm_id)[T.F173]            -0.1681      0.069     -2.432      0.015      -0.304      -0.033
C(firm_id)[T.F174]            -0.1543      0.120     -1.287      0.198      -0.389       0.081
C(firm_id)[T.F175]            -0.2146      0.165     -1.301      0.193      -0.538       0.109
C(firm_id)[T.F176]            -0.1696      0.174     -0.975      0.329      -0.510       0.171
C(firm_id)[T.F177]            -0.1581      0.189     -0.837      0.402      -0.528       0.212
C(firm_id)[T.F178]            -0.2284      0.115     -1.992      0.046      -0.453      -0.004
C(firm_id)[T.F179]            -0.2328      0.139     -1.680      0.093      -0.504       0.039
C(firm_id)[T.F180]            -0.1314      0.228     -0.576      0.565      -0.579       0.316
C(firm_id)[T.F181]            -0.0652      0.116     -0.562      0.574      -0.293       0.162
C(firm_id)[T.F182]            -0.1381      0.094     -1.471      0.141      -0.322       0.046
C(firm_id)[T.F183]            -0.1451      0.196     -0.741      0.458      -0.529       0.238
C(firm_id)[T.F184]            -0.2269      0.109     -2.080      0.038      -0.441      -0.013
C(firm_id)[T.F185]            -0.0557      0.241     -0.231      0.817      -0.527       0.416
C(firm_id)[T.F186]            -0.2334      0.104     -2.235      0.025      -0.438      -0.029
C(firm_id)[T.F187]            -0.1010      0.200     -0.504      0.614      -0.494       0.292
C(firm_id)[T.F188]            -0.2570      0.141     -1.829      0.067      -0.532       0.018
C(firm_id)[T.F189]            -0.1547      0.241     -0.642      0.521      -0.627       0.317
C(firm_id)[T.F190]            -0.1051      0.175     -0.600      0.548      -0.448       0.238
C(firm_id)[T.F191]            -0.0997      0.070     -1.427      0.154      -0.237       0.037
C(firm_id)[T.F192]            -0.1904      0.124     -1.532      0.125      -0.434       0.053
C(firm_id)[T.F193]            -0.2399      0.130     -1.843      0.065      -0.495       0.015
C(firm_id)[T.F194]            -0.1431      0.142     -1.008      0.313      -0.421       0.135
C(firm_id)[T.F195]            -0.2193      0.100     -2.190      0.029      -0.416      -0.023
C(firm_id)[T.F196]            -0.1992      0.160     -1.243      0.214      -0.513       0.115
C(firm_id)[T.F197]            -0.2142      0.114     -1.873      0.061      -0.438       0.010
C(firm_id)[T.F198]            -0.0811      0.195     -0.415      0.678      -0.464       0.302
C(firm_id)[T.F199]            -0.0563      0.272     -0.207      0.836      -0.589       0.476
C(fiscal_year)[T.2024]         0.0016      0.009      0.179      0.858      -0.016       0.019
C(fiscal_year)[T.2025]         0.0107      0.011      0.969      0.332      -0.011       0.032
policy_rate_change            -0.0028      0.004     -0.740      0.459      -0.010       0.005
leverage_lag                   0.0369      0.081      0.458      0.647      -0.121       0.195
rate_change_x_leverage_lag     0.0163      0.012      1.303      0.192      -0.008       0.041
size_ln_assets                 0.0173      0.055      0.314      0.753      -0.091       0.125
==============================================================================
Omnibus:                      110.736   Durbin-Watson:                   2.573
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              749.136

In [ ]:
main_vars = [
    "policy_rate_change",
    "leverage_lag",
    "rate_change_x_leverage_lag",
    "size_ln_assets"
]

results_roa_ebit = pd.DataFrame({
    "coef": model_roa_ebit.params[main_vars],
    "std_err": model_roa_ebit.bse[main_vars],
    "t_stat": model_roa_ebit.tvalues[main_vars],
    "p_value": model_roa_ebit.pvalues[main_vars]
})

print(results_roa_ebit)

print("\nN observations :", int(model_roa_ebit.nobs))
print("R² :", round(model_roa_ebit.rsquared, 4))
print("Adj. R² :", round(model_roa_ebit.rsquared_adj, 4))

print("\nCoefficient clé :")
print("rate_change_x_leverage_lag =", round(model_roa_ebit.params["rate_change_x_leverage_lag"], 6))
print("p-value =", round(model_roa_ebit.pvalues["rate_change_x_leverage_lag"], 6))

                                coef   std_err    t_stat   p_value
policy_rate_change         -0.002777  0.003752 -0.740109  0.459234
leverage_lag                0.036917  0.080540  0.458364  0.646691
rate_change_x_leverage_lag  0.016263  0.012479  1.303222  0.192499
size_ln_assets              0.017288  0.055047  0.314060  0.753476

N observations : 561
R² : 0.8737
Adj. R² : 0.8056

Coefficient clé :
rate_change_x_leverage_lag = 0.016263
p-value = 0.192499

In [ ]:
import pandas as pd
import statsmodels.formula.api as smf

file_path = "/content/final_regression_dataset_v2.xlsx"   # adapte si besoin
df = pd.read_excel(file_path, sheet_name="regression_base")

reg_cols = [
    "firm_id",
    "fiscal_year",
    "interest_coverage",
    "policy_rate_change",
    "leverage_lag",
    "rate_change_x_leverage_lag",
    "size_ln_assets"
]

reg3 = df[reg_cols].dropna().copy()

print("Observations:", len(reg3))
print("Firmes:", reg3["firm_id"].nunique())
print("Années:", sorted(reg3["fiscal_year"].unique()))

model_ic = smf.ols(
    "interest_coverage ~ policy_rate_change + leverage_lag + rate_change_x_leverage_lag + size_ln_assets + C(firm_id) + C(fiscal_year)",
    data=reg3
).fit(cov_type="cluster", cov_kwds={"groups": reg3["firm_id"]})

print(model_ic.summary())

Observations: 556
Firmes: 190
Années: [np.int64(2023), np.int64(2024), np.int64(2025)]
                            OLS Regression Results
==============================================================================
Dep. Variable:      interest_coverage   R-squared:                       0.636
Model:                            OLS   Adj. R-squared:                  0.440
Method:                 Least Squares   F-statistic:                     23.07
Date:                Tue, 31 Mar 2026   Prob (F-statistic):           2.37e-20
Time:                        13:46:42   Log-Likelihood:                -2912.5
No. Observations:                 556   AIC:                             6217.
Df Residuals:                     360   BIC:                             7064.
Df Model:                         195
Covariance Type:              cluster
==============================================================================================
                                 coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                  -2048.8905   1671.236     -1.226      0.220   -5324.454    1226.673
C(firm_id)[T.F002]           -31.8427     37.475     -0.850      0.395    -105.293      41.608
C(firm_id)[T.F003]           253.1549    106.451      2.378      0.017      44.515     461.795
C(firm_id)[T.F004]           -81.5072     55.558     -1.467      0.142    -190.400      27.385
C(firm_id)[T.F005]           193.6301     55.184      3.509      0.000      85.472     301.788
C(firm_id)[T.F006]            45.0924     41.044      1.099      0.272     -35.352     125.536
C(firm_id)[T.F007]           101.6240     82.790      1.227      0.220     -60.641     263.890
C(firm_id)[T.F008]           118.6566     95.505      1.242      0.214     -68.530     305.844
C(firm_id)[T.F010]           192.3204    155.694      1.235      0.217    -112.833     497.474
C(firm_id)[T.F011]            50.4860     74.288      0.680      0.497     -95.116     196.088
C(firm_id)[T.F012]            75.0652     67.658      1.109      0.267     -57.542     207.673
C(firm_id)[T.F013]           222.0587    177.530      1.251      0.211    -125.894     570.012
C(firm_id)[T.F014]           173.9148    156.107      1.114      0.265    -132.049     479.878
C(firm_id)[T.F015]            75.0370    105.035      0.714      0.475    -130.829     280.903
C(firm_id)[T.F016]           187.5545    153.518      1.222      0.222    -113.336     488.445
C(firm_id)[T.F017]           136.0355    121.427      1.120      0.263    -101.957     374.028
C(firm_id)[T.F018]           178.1911    150.133      1.187      0.235    -116.065     472.447
C(firm_id)[T.F019]            91.4927    105.534      0.867      0.386    -115.350     298.335
C(firm_id)[T.F020]           268.5694    210.309      1.277      0.202    -143.628     680.767
C(firm_id)[T.F021]           237.1727    188.221      1.260      0.208    -131.733     606.079
C(firm_id)[T.F022]           441.8121    188.207      2.347      0.019      72.932     810.692
C(firm_id)[T.F023]           223.9288    219.538      1.020      0.308    -206.357     654.215
C(firm_id)[T.F024]            10.0175     39.300      0.255      0.799     -67.009      87.044
C(firm_id)[T.F025]            55.2841     60.020      0.921      0.357     -62.353     172.922
C(firm_id)[T.F026]           145.4795    114.169      1.274      0.203     -78.288     369.247
C(firm_id)[T.F027]           124.1809    103.764      1.197      0.231     -79.193     327.555
C(firm_id)[T.F028]            32.5455     47.113      0.691      0.490     -59.794     124.885
C(firm_id)[T.F029]            78.8238     71.042      1.110      0.267     -60.416     218.064
C(firm_id)[T.F030]            76.1201     72.149      1.055      0.291     -65.290     217.530
C(firm_id)[T.F031]             9.5450     34.599      0.276      0.783     -58.267      77.357
C(firm_id)[T.F032]            88.3993     83.770      1.055      0.291     -75.787     252.585
C(firm_id)[T.F033]            89.9096     95.103      0.945      0.344     -96.489     276.308
C(firm_id)[T.F034]            96.7771     94.089      1.029      0.304     -87.633     281.187
C(firm_id)[T.F036]           157.5203    141.599      1.112      0.266    -120.009     435.049
C(firm_id)[T.F037]           152.0821    135.706      1.121      0.262    -113.897     418.062
C(firm_id)[T.F038]           252.7049    185.506      1.362      0.173    -110.880     616.290
C(firm_id)[T.F039]           279.7802    214.429      1.305      0.192    -140.493     700.053
C(firm_id)[T.F040]           -15.1956     20.400     -0.745      0.456     -55.179      24.788
C(firm_id)[T.F041]            72.9603     86.337      0.845      0.398     -96.257     242.178
C(firm_id)[T.F042]           184.8928    142.881      1.294      0.196     -95.150     464.935
C(firm_id)[T.F043]            -6.3354     26.685     -0.237      0.812     -58.637      45.966
C(firm_id)[T.F044]           199.5040    149.604      1.334      0.182     -93.714     492.723
C(firm_id)[T.F045]            28.0944     55.252      0.508      0.611     -80.198     136.387
C(firm_id)[T.F046]           141.8938    123.718      1.147      0.251    -100.588     384.376
C(firm_id)[T.F047]            17.3090     39.268      0.441      0.659     -59.655      94.273
C(firm_id)[T.F048]            13.0616     24.007      0.544      0.586     -33.991      60.114
C(firm_id)[T.F049]            31.9339     38.622      0.827      0.408     -43.764     107.631
C(firm_id)[T.F050]           -19.9085      6.250     -3.185      0.001     -32.159      -7.658
C(firm_id)[T.F051]           129.5119    125.750      1.030      0.303    -116.953     375.976
C(firm_id)[T.F052]           236.1074    181.637      1.300      0.194    -119.894     592.109
C(firm_id)[T.F053]           175.9802    176.830      0.995      0.320    -170.601     522.561
C(firm_id)[T.F054]           247.4436    212.437      1.165      0.244    -168.926     663.813
C(firm_id)[T.F055]           219.8080    170.303      1.291      0.197    -113.979     553.595
C(firm_id)[T.F056]           437.4037    142.607      3.067      0.002     157.900     716.908
C(firm_id)[T.F057]           235.9221    172.022      1.371      0.170    -101.235     573.079
C(firm_id)[T.F058]           153.5895    115.008      1.335      0.182     -71.822     379.001
C(firm_id)[T.F059]           212.9157    157.053      1.356      0.175     -94.903     520.735
C(firm_id)[T.F060]           281.2601    235.032      1.197      0.231    -179.393     741.914
C(firm_id)[T.F061]           -11.0211     34.898     -0.316      0.752     -79.419      57.377
C(firm_id)[T.F062]           124.9605    118.272      1.057      0.291    -106.849     356.770
C(firm_id)[T.F063]            71.5402     69.442      1.030      0.303     -64.564     207.644
C(firm_id)[T.F064]           103.3887     88.934      1.163      0.245     -70.919     277.696
C(firm_id)[T.F065]           111.2304     89.699      1.240      0.215     -64.577     287.038
C(firm_id)[T.F066]           197.4202    145.623      1.356      0.175     -87.996     482.837
C(firm_id)[T.F067]           121.3030    120.681      1.005      0.315    -115.227     357.832
C(firm_id)[T.F068]           271.7546    208.469      1.304      0.192    -136.837     680.346
C(firm_id)[T.F069]           119.4772     91.774      1.302      0.193     -60.396     299.351
C(firm_id)[T.F070]           128.8029    102.430      1.257      0.209     -71.955     329.561
C(firm_id)[T.F071]           111.5578    105.421      1.058      0.290     -95.064     318.180
C(firm_id)[T.F072]           109.5103    117.290      0.934      0.350    -120.373     339.394
C(firm_id)[T.F073]            29.9363     50.756      0.590      0.555     -69.543     129.416
C(firm_id)[T.F074]           141.4902    122.333      1.157      0.247     -98.277     381.258
C(firm_id)[T.F075]            55.2841     60.020      0.921      0.357     -62.353     172.922
C(firm_id)[T.F076]           107.6339    103.451      1.040      0.298     -95.125     310.393
C(firm_id)[T.F077]           120.3377     99.065      1.215      0.224     -73.826     314.501
C(firm_id)[T.F078]           145.0390    116.988      1.240      0.215     -84.254     374.332
C(firm_id)[T.F079]           173.4104    142.900      1.214      0.225    -106.668     453.489
C(firm_id)[T.F080]           172.6770    141.023      1.224      0.221    -103.723     449.078
C(firm_id)[T.F081]           191.2730    162.314      1.178      0.239    -126.856     509.402
C(firm_id)[T.F082]           214.3383    183.094      1.171      0.242    -144.519     573.196
C(firm_id)[T.F083]           214.0785    200.893      1.066      0.287    -179.664     607.821
C(firm_id)[T.F084]           210.9968    178.254      1.184      0.237    -138.375     560.368
C(firm_id)[T.F085]           219.1175    193.271      1.134      0.257    -159.686     597.921
C(firm_id)[T.F086]           108.8053     95.009      1.145      0.252     -77.410     295.020
C(firm_id)[T.F087]           171.4361    147.124      1.165      0.244    -116.921     459.794
C(firm_id)[T.F088]           121.5514    118.278      1.028      0.304    -110.268     353.371
C(firm_id)[T.F089]           -14.5716     41.404     -0.352      0.725     -95.723      66.579
C(firm_id)[T.F090]            -4.4068     43.691     -0.101      0.920     -90.039      81.226
C(firm_id)[T.F091]          -359.4847    340.731     -1.055      0.291   -1027.305     308.335
C(firm_id)[T.F092]          -380.2611    294.475     -1.291      0.197    -957.422     196.899
C(firm_id)[T.F093]          -185.8906    152.816     -1.216      0.224    -485.405     113.624
C(firm_id)[T.F095]            98.9560    186.138      0.532      0.595    -265.868     463.780
C(firm_id)[T.F096]          -315.9960    230.417     -1.371      0.170    -767.605     135.613
C(firm_id)[T.F098]          -348.5238    272.008     -1.281      0.200    -881.651     184.603
C(firm_id)[T.F099]          -180.0154    143.807     -1.252      0.211    -461.872     101.841
C(firm_id)[T.F102]          -141.8465    108.830     -1.303      0.192    -355.149      71.456
C(firm_id)[T.F104]          -210.0119    151.286     -1.388      0.165    -506.528      86.504
C(firm_id)[T.F105]           -23.2182     96.588     -0.240      0.810    -212.527     166.091
C(firm_id)[T.F106]          -280.3819    206.222     -1.360      0.174    -684.570     123.806
C(firm_id)[T.F107]          -377.6048    283.094     -1.334      0.182    -932.459     177.249
C(firm_id)[T.F108]          -234.2611    166.389     -1.408      0.159    -560.377      91.855
C(firm_id)[T.F109]          -255.2780    237.674     -1.074      0.283    -721.110     210.554
C(firm_id)[T.F110]          -303.8527    230.357     -1.319      0.187    -755.344     147.638
C(firm_id)[T.F111]           -38.7678     23.017     -1.684      0.092     -83.881       6.345
C(firm_id)[T.F112]            80.9921     79.984      1.013      0.311     -75.774     237.758
C(firm_id)[T.F113]           126.6962    105.673      1.199      0.231     -80.419     333.811
C(firm_id)[T.F114]           265.1889    209.650      1.265      0.206    -145.717     676.095
C(firm_id)[T.F115]           -11.0305     23.430     -0.471      0.638     -56.951      34.891
C(firm_id)[T.F116]           133.3737    117.044      1.140      0.254     -96.029     362.777
C(firm_id)[T.F117]           177.1937    141.314      1.254      0.210     -99.777     454.165
C(firm_id)[T.F118]            72.6626     75.300      0.965      0.335     -74.922     220.247
C(firm_id)[T.F119]           198.8473    168.738      1.178      0.239    -131.873     529.567
C(firm_id)[T.F120]            53.1938     77.237      0.689      0.491     -98.187     204.575
C(firm_id)[T.F121]            54.3172     66.053      0.822      0.411     -75.145     183.779
C(firm_id)[T.F122]           112.7242    112.548      1.002      0.317    -107.866     333.314
C(firm_id)[T.F123]            76.3195     68.917      1.107      0.268     -58.756     211.395
C(firm_id)[T.F124]           184.8037    167.029      1.106      0.269    -142.568     512.176
C(firm_id)[T.F125]           195.6899    172.482      1.135      0.257    -142.369     533.749
C(firm_id)[T.F126]           174.7735    151.299      1.155      0.248    -121.768     471.315
C(firm_id)[T.F127]           136.2013    120.858      1.127      0.260    -100.676     373.079
C(firm_id)[T.F128]            84.3166     91.996      0.917      0.359     -95.992     264.626
C(firm_id)[T.F129]           135.8097    112.819      1.204      0.229     -85.312     356.931
C(firm_id)[T.F130]           200.0879    186.368      1.074      0.283    -165.187     565.363
C(firm_id)[T.F131]            78.2180     91.198      0.858      0.391    -100.526     256.962
C(firm_id)[T.F132]            70.9000     87.495      0.810      0.418    -100.586     242.386
C(firm_id)[T.F133]           201.8756    204.684      0.986      0.324    -199.298     603.049
C(firm_id)[T.F134]           245.1734    211.957      1.157      0.247    -170.255     660.602
C(firm_id)[T.F135]           112.1275    125.361      0.894      0.371    -133.576     357.831
C(firm_id)[T.F136]           223.2824    152.763      1.462      0.144     -76.127     522.692
C(firm_id)[T.F138]           258.1791    225.622      1.144      0.252    -184.031     700.389
C(firm_id)[T.F140]           152.2310    127.543      1.194      0.233     -97.749     402.211
C(firm_id)[T.F141]            63.0671     59.741      1.056      0.291     -54.023     180.157
C(firm_id)[T.F142]           246.1552    173.737      1.417      0.157     -94.364     586.674
C(firm_id)[T.F143]           127.6426    117.202      1.089      0.276    -102.069     357.354
C(firm_id)[T.F144]            32.2690     70.907      0.455      0.649    -106.707     171.245
C(firm_id)[T.F145]            -8.3364     26.905     -0.310      0.757     -61.068      44.396
C(firm_id)[T.F146]            43.9915     67.988      0.647      0.518     -89.263     177.246
C(firm_id)[T.F147]           116.5957    111.551      1.045      0.296    -102.041     335.233
C(firm_id)[T.F148]           185.0996    125.388      1.476      0.140     -60.656     430.856
C(firm_id)[T.F149]           194.2833    166.973      1.164      0.245    -132.977     521.544
C(firm_id)[T.F150]            62.6423     68.150      0.919      0.358     -70.930     196.215
C(firm_id)[T.F151]           143.0930    140.093      1.021      0.307    -131.484     417.670
C(firm_id)[T.F152]           170.0681    146.099      1.164      0.244    -116.281     456.417
C(firm_id)[T.F153]           100.5059    117.559      0.855      0.393    -129.906     330.918
C(firm_id)[T.F154]           115.5068    111.909      1.032      0.302    -103.832     334.845
C(firm_id)[T.F155]           106.5498     87.127      1.223      0.221     -64.216     277.315
C(firm_id)[T.F156]            95.1833    103.323      0.921      0.357    -107.326     297.693
C(firm_id)[T.F157]            58.1844     58.113      1.001      0.317     -55.716     172.084
C(firm_id)[T.F158]            24.2751     23.743      1.022      0.307     -22.261      70.811
C(firm_id)[T.F159]            32.9224     25.057      1.314      0.189     -16.188      82.033
C(firm_id)[T.F160]           -59.5570     32.670     -1.823      0.068    -123.589       4.475
C(firm_id)[T.F161]            98.7592     98.791      1.000      0.317     -94.868     292.386
C(firm_id)[T.F162]            81.7285     79.967      1.022      0.307     -75.003     238.461
C(firm_id)[T.F163]           176.7407    158.860      1.113      0.266    -134.619     488.100
C(firm_id)[T.F164]            27.1273     34.407      0.788      0.430     -40.309      94.564
C(firm_id)[T.F165]           119.7511    107.806      1.111      0.267     -91.544     331.047
C(firm_id)[T.F166]           216.4310    186.961      1.158      0.247    -150.006     582.868
C(firm_id)[T.F167]           232.4383    208.453      1.115      0.265    -176.121     640.998
C(firm_id)[T.F168]           223.8388    203.588      1.099      0.272    -175.186     622.863
C(firm_id)[T.F169]           103.2924    130.421      0.792      0.428    -152.327     358.912
C(firm_id)[T.F170]           134.8537    124.958      1.079      0.281    -110.060     379.767
C(firm_id)[T.F171]            91.0166     74.920      1.215      0.224     -55.824     237.857
C(firm_id)[T.F172]           102.7471     87.336      1.176      0.239     -68.429     273.923
C(firm_id)[T.F173]            87.6021     80.978      1.082      0.279     -71.111     246.316
C(firm_id)[T.F174]           189.6259    136.796      1.386      0.166     -78.489     457.741
C(firm_id)[T.F175]           209.2703    188.207      1.112      0.266    -159.609     578.150
C(firm_id)[T.F176]           253.5747    205.586      1.233      0.217    -149.367     656.516
C(firm_id)[T.F177]           287.5361    225.925      1.273      0.203    -155.268     730.341
C(firm_id)[T.F178]           142.4039    132.218      1.077      0.281    -116.740     401.547
C(firm_id)[T.F179]           154.0209    155.729      0.989      0.323    -151.203     459.244
C(firm_id)[T.F180]           340.0831    265.266      1.282      0.200    -179.828     859.995
C(firm_id)[T.F181]           180.9078    129.729      1.395      0.163     -73.356     435.171
C(firm_id)[T.F182]           122.8196    108.282      1.134      0.257     -89.409     335.048
C(firm_id)[T.F183]           315.6133    217.660      1.450      0.147    -110.992     742.219
C(firm_id)[T.F184]           153.9260    131.623      1.169      0.242    -104.051     411.903
C(firm_id)[T.F185]           767.8100    268.026      2.865      0.004     242.489    1293.131
C(firm_id)[T.F186]           137.5808    123.353      1.115      0.265    -104.186     379.348
C(firm_id)[T.F187]           305.1490    238.458      1.280      0.201    -162.221     772.519
C(firm_id)[T.F188]           174.5615    161.789      1.079      0.281    -142.539     491.662
C(firm_id)[T.F189]           336.7464    279.692      1.204      0.229    -211.441     884.934
C(firm_id)[T.F190]           235.6241    200.543      1.175      0.240    -157.433     628.682
C(firm_id)[T.F191]            69.7918     79.858      0.874      0.382     -86.726     226.310
C(firm_id)[T.F192]           173.2968    146.729      1.181      0.238    -114.287     460.880
C(firm_id)[T.F193]           209.4724    162.573      1.288      0.198    -109.165     528.110
C(firm_id)[T.F194]           232.1506    172.156      1.348      0.178    -105.270     569.571
C(firm_id)[T.F195]           107.6966    112.793      0.955      0.340    -113.373     328.766
C(firm_id)[T.F196]           268.9410    197.961      1.359      0.174    -119.056     656.938
C(firm_id)[T.F197]           160.1620    136.588      1.173      0.241    -107.545     427.869
C(firm_id)[T.F198]           265.2546    224.735      1.180      0.238    -175.217     705.726
C(firm_id)[T.F199]           383.6544    306.211      1.253      0.210    -216.507     983.816
C(fiscal_year)[T.2024]       -32.4216     23.114     -1.403      0.161     -77.724      12.881
C(fiscal_year)[T.2025]       -31.8814     26.425     -1.206      0.228     -83.674      19.911
policy_rate_change           -13.9910     12.532     -1.116      0.264     -38.554      10.572
leverage_lag                -174.2480    169.406     -1.029      0.304    -506.277     157.781
rate_change_x_leverage_lag    11.5099     23.760      0.484      0.628     -35.059      58.079
size_ln_assets                80.7081     63.415      1.273      0.203     -43.584     205.000
==============================================================================
Omnibus:                      418.149   Durbin-Watson:                   2.249
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            68997.239

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 195, but rank is 6
  warnings.warn('covariance of constraints does not have full '

In [ ]:
main_vars = [
    "policy_rate_change",
    "leverage_lag",
    "rate_change_x_leverage_lag",
    "size_ln_assets"
]

results_ic = pd.DataFrame({
    "coef": model_ic.params[main_vars],
    "std_err": model_ic.bse[main_vars],
    "t_stat": model_ic.tvalues[main_vars],
    "p_value": model_ic.pvalues[main_vars]
})

print(results_ic)

print("\nN observations :", int(model_ic.nobs))
print("R² :", round(model_ic.rsquared, 4))
print("Adj. R² :", round(model_ic.rsquared_adj, 4))

print("\nCoefficient clé :")
print("rate_change_x_leverage_lag =", round(model_ic.params["rate_change_x_leverage_lag"], 6))
print("p-value =", round(model_ic.pvalues["rate_change_x_leverage_lag"], 6))

                                  coef     std_err    t_stat   p_value
policy_rate_change          -13.990963   12.532394 -1.116384  0.264258
leverage_lag               -174.248008  169.405548 -1.028585  0.303675
rate_change_x_leverage_lag   11.509904   23.760149  0.484421  0.628087
size_ln_assets               80.708062   63.415400  1.272689  0.203129

N observations : 556
R² : 0.6365
Adj. R² : 0.4395

Coefficient clé :
rate_change_x_leverage_lag = 11.509904
p-value = 0.628087

In [2]:
import pandas as pd
import statsmodels.formula.api as smf

file_path = "/content/final_regression_dataset_v2.xlsx"   # adapte si besoin
df = pd.read_excel(file_path, sheet_name="regression_base")

print(df.shape)
df.head()

(781, 30)

,firm_id,ticker,company_name,country,macro_zone,sector,fiscal_year,roa,roa_ebit,interest_coverage,...,ebit,ebitda,interest_expense,net_income,total_assets,total_debt,source_primary,data_quality_score,notes,interest_coverage_raw_backup
0,F001,AAPL,Apple Inc.,United States,US,Technology,2022,0.282924,0.323701,40.749574,...,1.194370e+11,1.305410e+11,2.931000e+09,9.980300e+10,3.527550e+11,1.118240e+11,Yahoo + SEC override,1.000,NaN,40.749574
1,F001,AAPL,Apple Inc.,United States,US,Technology,2023,0.275098,0.323701,29.062039,...,1.143010e+11,1.258200e+11,3.933000e+09,9.699500e+10,3.525830e+11,1.065720e+11,Yahoo + SEC override,1.000,NaN,29.062039
2,F001,AAPL,Apple Inc.,United States,US,Technology,2024,0.256825,0.323701,NaN,...,1.232160e+11,1.346610e+11,NaN,9.373600e+10,3.649800e+11,9.734100e+10,Yahoo + SEC override,0.875,NaN,NaN
3,F001,AAPL,Apple Inc.,United States,US,Technology,2025,0.306894,0.323701,NaN,...,1.330500e+11,1.447480e+11,NaN,1.120100e+11,3.649800e+11,9.128100e+10,Yahoo + SEC override,0.875,NaN,NaN
4,F002,MSFT,Microsoft Corporation,United States,US,Technology,2022,0.121371,0.145157,20.439599,...,5.295900e+10,1.002390e+11,2.591000e+09,4.428100e+10,3.648400e+11,5.551100e+10,Yahoo + SEC override,1.000,NaN,20.439599

In [4]:
reg_cols = [
    "firm_id",
    "fiscal_year",
    "roa",
    "policy_rate_fye",
    "leverage_lag",
    "rate_x_leverage_lag",
    "size_ln_assets"
]

reg_level_roa = df[reg_cols].dropna().copy()

print("Observations:", len(reg_level_roa))
print("Firmes:", reg_level_roa["firm_id"].nunique())
print("Années:", sorted(reg_level_roa["fiscal_year"].unique()))

Observations: 561
Firmes: 191
Années: [np.int64(2023), np.int64(2024), np.int64(2025)]

In [5]:
model_level_roa = smf.ols(
    "roa ~ policy_rate_fye + leverage_lag + rate_x_leverage_lag + size_ln_assets + C(firm_id) + C(fiscal_year)",
    data=reg_level_roa
).fit(cov_type="cluster", cov_kwds={"groups": reg_level_roa["firm_id"]})

print(model_level_roa.summary())

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 196, but rank is 6
  warnings.warn('covariance of constraints does not have full '

                            OLS Regression Results
==============================================================================
Dep. Variable:                    roa   R-squared:                       0.800
Model:                            OLS   Adj. R-squared:                  0.693
Method:                 Least Squares   F-statistic:                     376.6
Date:                Sun, 05 Apr 2026   Prob (F-statistic):          1.29e-102
Time:                        22:44:16   Log-Likelihood:                 1167.1
No. Observations:                 561   AIC:                            -1940.
Df Residuals:                     364   BIC:                            -1087.
Df Model:                         196
Covariance Type:              cluster
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 -0.8399      3.298     -0.255      0.799      -7.303       5.623
C(firm_id)[T.F002]        -0.1003      0.036     -2.787      0.005      -0.171      -0.030
C(firm_id)[T.F003]         0.1957      0.208      0.939      0.348      -0.213       0.604
C(firm_id)[T.F004]        -0.2225      0.078     -2.848      0.004      -0.376      -0.069
C(firm_id)[T.F005]        -0.0825      0.047     -1.768      0.077      -0.174       0.009
C(firm_id)[T.F006]        -0.0823      0.032     -2.588      0.010      -0.145      -0.020
C(firm_id)[T.F007]        -0.1121      0.137     -0.818      0.413      -0.381       0.157
C(firm_id)[T.F008]        -0.1617      0.131     -1.233      0.217      -0.419       0.095
C(firm_id)[T.F009]        -0.1743      0.153     -1.136      0.256      -0.475       0.126
C(firm_id)[T.F010]         0.0273      0.307      0.089      0.929      -0.574       0.629
C(firm_id)[T.F011]        -0.1348      0.138     -0.975      0.329      -0.406       0.136
C(firm_id)[T.F012]        -0.1826      0.120     -1.526      0.127      -0.417       0.052
C(firm_id)[T.F013]        -0.0787      0.351     -0.225      0.822      -0.766       0.608
C(firm_id)[T.F014]        -0.0898      0.306     -0.293      0.770      -0.691       0.511
C(firm_id)[T.F015]        -0.1798      0.198     -0.906      0.365      -0.569       0.209
C(firm_id)[T.F016]        -0.0178      0.295     -0.060      0.952      -0.596       0.560
C(firm_id)[T.F017]        -0.0563      0.237     -0.238      0.812      -0.520       0.408
C(firm_id)[T.F018]         0.0340      0.296      0.115      0.909      -0.545       0.613
C(firm_id)[T.F019]        -0.1931      0.206     -0.937      0.349      -0.597       0.211
C(firm_id)[T.F020]         0.0836      0.400      0.209      0.835      -0.701       0.868
C(firm_id)[T.F021]         0.1040      0.368      0.282      0.778      -0.617       0.825
C(firm_id)[T.F022]        -0.0809      0.372     -0.218      0.828      -0.810       0.648
C(firm_id)[T.F023]         0.0864      0.435      0.199      0.843      -0.766       0.939
C(firm_id)[T.F024]        -0.2836      0.073     -3.898      0.000      -0.426      -0.141
C(firm_id)[T.F025]        -0.2693      0.109     -2.478      0.013      -0.482      -0.056
C(firm_id)[T.F026]        -0.1542      0.178     -0.864      0.387      -0.504       0.195
C(firm_id)[T.F027]        -0.0826      0.184     -0.449      0.653      -0.443       0.278
C(firm_id)[T.F028]        -0.1095      0.084     -1.309      0.191      -0.273       0.054
C(firm_id)[T.F029]        -0.2037      0.126     -1.619      0.105      -0.450       0.043
C(firm_id)[T.F030]        -0.1375      0.138     -0.998      0.318      -0.407       0.133
C(firm_id)[T.F031]        -0.2285      0.063     -3.630      0.000      -0.352      -0.105
C(firm_id)[T.F032]        -0.1633      0.159     -1.030      0.303      -0.474       0.147
C(firm_id)[T.F033]        -0.1096      0.186     -0.591      0.555      -0.474       0.254
C(firm_id)[T.F034]        -0.1663      0.184     -0.906      0.365      -0.526       0.194
C(firm_id)[T.F036]        -0.1318      0.276     -0.477      0.633      -0.673       0.409
C(firm_id)[T.F037]        -0.1526      0.264     -0.579      0.563      -0.670       0.364
C(firm_id)[T.F038]        -0.0523      0.304     -0.172      0.864      -0.649       0.544
C(firm_id)[T.F039]         0.0281      0.404      0.070      0.945      -0.763       0.819
C(firm_id)[T.F040]        -0.2115      0.025     -8.440      0.000      -0.261      -0.162
C(firm_id)[T.F041]        -0.1965      0.167     -1.175      0.240      -0.524       0.131
C(firm_id)[T.F042]        -0.0669      0.280     -0.239      0.811      -0.616       0.482
C(firm_id)[T.F043]        -0.2446      0.044     -5.602      0.000      -0.330      -0.159
C(firm_id)[T.F044]        -0.0849      0.238     -0.357      0.721      -0.551       0.382
C(firm_id)[T.F045]        -0.2106      0.103     -2.041      0.041      -0.413      -0.008
C(firm_id)[T.F046]        -0.0401      0.240     -0.167      0.867      -0.511       0.430
C(firm_id)[T.F047]        -0.2210      0.073     -3.035      0.002      -0.364      -0.078
C(firm_id)[T.F048]        -0.2036      0.039     -5.253      0.000      -0.280      -0.128
C(firm_id)[T.F049]        -0.2079      0.068     -3.062      0.002      -0.341      -0.075
C(firm_id)[T.F050]        -0.2421      0.010    -24.605      0.000      -0.261      -0.223
C(firm_id)[T.F051]        -0.0584      0.246     -0.237      0.813      -0.541       0.424
C(firm_id)[T.F052]         0.0237      0.329      0.072      0.943      -0.621       0.669
C(firm_id)[T.F053]        -0.0018      0.350     -0.005      0.996      -0.687       0.683
C(firm_id)[T.F054]        -0.0799      0.414     -0.193      0.847      -0.891       0.732
C(firm_id)[T.F055]        -0.0674      0.312     -0.216      0.829      -0.680       0.545
C(firm_id)[T.F056]        -0.0602      0.280     -0.215      0.829      -0.608       0.488
C(firm_id)[T.F057]        -0.0383      0.270     -0.142      0.887      -0.568       0.491
C(firm_id)[T.F058]        -0.0310      0.188     -0.165      0.869      -0.400       0.338
C(firm_id)[T.F059]        -0.0268      0.310     -0.087      0.931      -0.634       0.580
C(firm_id)[T.F060]         0.0535      0.460      0.116      0.907      -0.849       0.956
C(firm_id)[T.F061]        -0.1945      0.045     -4.330      0.000      -0.282      -0.106
C(firm_id)[T.F062]        -0.1366      0.231     -0.591      0.555      -0.590       0.316
C(firm_id)[T.F063]        -0.1078      0.134     -0.804      0.421      -0.371       0.155
C(firm_id)[T.F064]        -0.1083      0.163     -0.663      0.507      -0.428       0.212
C(firm_id)[T.F065]        -0.1330      0.163     -0.814      0.416      -0.453       0.187
C(firm_id)[T.F066]        -0.0729      0.226     -0.323      0.747      -0.515       0.369
C(firm_id)[T.F067]        -0.1624      0.236     -0.688      0.492      -0.625       0.301
C(firm_id)[T.F068]         0.0121      0.391      0.031      0.975      -0.754       0.779
C(firm_id)[T.F069]        -0.1100      0.173     -0.636      0.525      -0.449       0.229
C(firm_id)[T.F070]        -0.1562      0.161     -0.971      0.332      -0.472       0.159
C(firm_id)[T.F071]        -0.1309      0.204     -0.641      0.521      -0.531       0.269
C(firm_id)[T.F072]        -0.1331      0.230     -0.578      0.563      -0.584       0.318
C(firm_id)[T.F073]        -0.2147      0.096     -2.232      0.026      -0.403      -0.026
C(firm_id)[T.F074]        -0.0953      0.234     -0.408      0.683      -0.553       0.362
C(firm_id)[T.F075]        -0.2693      0.109     -2.478      0.013      -0.482      -0.056
C(firm_id)[T.F076]        -0.1255      0.201     -0.623      0.533      -0.520       0.269
C(firm_id)[T.F077]        -0.1711      0.180     -0.950      0.342      -0.524       0.182
C(firm_id)[T.F078]        -0.1092      0.212     -0.515      0.606      -0.525       0.306
C(firm_id)[T.F079]        -0.1101      0.268     -0.410      0.682      -0.636       0.416
C(firm_id)[T.F080]        -0.0882      0.271     -0.326      0.745      -0.619       0.442
C(firm_id)[T.F081]        -0.0772      0.313     -0.247      0.805      -0.691       0.537
C(firm_id)[T.F082]        -0.0311      0.353     -0.088      0.930      -0.724       0.661
C(firm_id)[T.F083]        -0.1328      0.397     -0.335      0.738      -0.910       0.645
C(firm_id)[T.F084]        -0.0807      0.345     -0.234      0.815      -0.756       0.594
C(firm_id)[T.F085]        -0.1195      0.377     -0.317      0.752      -0.859       0.620
C(firm_id)[T.F086]        -0.1370      0.183     -0.748      0.455      -0.496       0.222
C(firm_id)[T.F087]        -0.1274      0.285     -0.448      0.654      -0.685       0.430
C(firm_id)[T.F088]        -0.1253      0.232     -0.540      0.590      -0.580       0.330
C(firm_id)[T.F089]        -0.2059      0.030     -6.753      0.000      -0.266      -0.146
C(firm_id)[T.F090]        -0.2058      0.035     -5.951      0.000      -0.274      -0.138
C(firm_id)[T.F091]        -0.4439      0.697     -0.637      0.524      -1.811       0.923
C(firm_id)[T.F092]        -0.4463      0.578     -0.773      0.440      -1.579       0.686
C(firm_id)[T.F093]        -0.2778      0.300     -0.927      0.354      -0.865       0.309
C(firm_id)[T.F095]        -0.2934      0.345     -0.851      0.395      -0.969       0.382
C(firm_id)[T.F096]        -0.3821      0.457     -0.836      0.403      -1.278       0.514
C(firm_id)[T.F098]        -0.4055      0.559     -0.726      0.468      -1.500       0.689
C(firm_id)[T.F099]        -0.2567      0.273     -0.939      0.348      -0.792       0.279
C(firm_id)[T.F102]        -0.2898      0.211     -1.374      0.169      -0.703       0.124
C(firm_id)[T.F104]        -0.3198      0.282     -1.134      0.257      -0.872       0.233
C(firm_id)[T.F105]        -0.1834      0.160     -1.147      0.251      -0.497       0.130
C(firm_id)[T.F106]        -0.3746      0.402     -0.931      0.352      -1.163       0.414
C(firm_id)[T.F107]        -0.4387      0.557     -0.788      0.431      -1.530       0.653
C(firm_id)[T.F108]        -0.3305      0.335     -0.985      0.325      -0.988       0.327
C(firm_id)[T.F109]        -0.3888      0.471     -0.826      0.409      -1.312       0.534
C(firm_id)[T.F110]        -0.3639      0.473     -0.770      0.441      -1.290       0.563
C(firm_id)[T.F111]        -0.2368      0.014    -16.613      0.000      -0.265      -0.209
C(firm_id)[T.F112]        -0.1554      0.152     -1.019      0.308      -0.454       0.143
C(firm_id)[T.F113]        -0.1149      0.198     -0.581      0.561      -0.502       0.273
C(firm_id)[T.F114]        -0.0200      0.397     -0.050      0.960      -0.798       0.758
C(firm_id)[T.F115]        -0.2499      0.031     -8.118      0.000      -0.310      -0.190
C(firm_id)[T.F116]        -0.1297      0.225     -0.578      0.564      -0.570       0.310
C(firm_id)[T.F117]        -0.1145      0.259     -0.441      0.659      -0.623       0.394
C(firm_id)[T.F118]        -0.2389      0.142     -1.678      0.093      -0.518       0.040
C(firm_id)[T.F119]        -0.1080      0.324     -0.333      0.739      -0.744       0.528
C(firm_id)[T.F120]        -0.1334      0.145     -0.922      0.356      -0.417       0.150
C(firm_id)[T.F121]        -0.2218      0.116     -1.909      0.056      -0.449       0.006
C(firm_id)[T.F122]        -0.2409      0.218     -1.104      0.269      -0.668       0.187
C(firm_id)[T.F123]        -0.2229      0.119     -1.866      0.062      -0.457       0.011
C(firm_id)[T.F124]        -0.1531      0.324     -0.473      0.636      -0.788       0.482
C(firm_id)[T.F125]        -0.0966      0.337     -0.287      0.774      -0.757       0.563
C(firm_id)[T.F126]        -0.0922      0.290     -0.318      0.750      -0.660       0.476
C(firm_id)[T.F127]        -0.1067      0.230     -0.465      0.642      -0.557       0.343
C(firm_id)[T.F128]        -0.1686      0.178     -0.949      0.343      -0.517       0.180
C(firm_id)[T.F129]        -0.1649      0.196     -0.841      0.401      -0.549       0.220
C(firm_id)[T.F130]        -0.0364      0.367     -0.099      0.921      -0.756       0.683
C(firm_id)[T.F131]        -0.1173      0.177     -0.663      0.507      -0.464       0.229
C(firm_id)[T.F132]        -0.1445      0.170     -0.852      0.394      -0.477       0.188
C(firm_id)[T.F133]        -0.0616      0.406     -0.152      0.879      -0.857       0.733
C(firm_id)[T.F134]        -0.0868      0.410     -0.212      0.832      -0.891       0.717
C(firm_id)[T.F135]        -0.1384      0.246     -0.563      0.573      -0.620       0.343
C(firm_id)[T.F136]        -0.0906      0.301     -0.301      0.763      -0.680       0.499
C(firm_id)[T.F138]        -0.1163      0.438     -0.265      0.791      -0.975       0.743
C(firm_id)[T.F140]        -0.1766      0.228     -0.774      0.439      -0.624       0.271
C(firm_id)[T.F141]        -0.1479      0.109     -1.363      0.173      -0.361       0.065
C(firm_id)[T.F142]         0.0351      0.339      0.104      0.918      -0.630       0.700
C(firm_id)[T.F143]        -0.0902      0.225     -0.401      0.688      -0.531       0.351
C(firm_id)[T.F144]        -0.2034      0.124     -1.637      0.102      -0.447       0.040
C(firm_id)[T.F145]        -0.2016      0.024     -8.380      0.000      -0.249      -0.154
C(firm_id)[T.F146]        -0.1876      0.123     -1.525      0.127      -0.429       0.054
C(firm_id)[T.F147]        -0.1361      0.213     -0.639      0.523      -0.554       0.281
C(firm_id)[T.F148]        -0.1277      0.239     -0.533      0.594      -0.597       0.341
C(firm_id)[T.F149]        -0.1021      0.321     -0.318      0.750      -0.731       0.527
C(firm_id)[T.F150]        -0.1929      0.125     -1.541      0.123      -0.438       0.052
C(firm_id)[T.F151]        -0.1488      0.270     -0.550      0.582      -0.679       0.381
C(firm_id)[T.F152]        -0.1301      0.276     -0.472      0.637      -0.671       0.411
C(firm_id)[T.F153]        -0.1862      0.226     -0.824      0.410      -0.629       0.257
C(firm_id)[T.F154]        -0.1848      0.213     -0.868      0.385      -0.602       0.233
C(firm_id)[T.F155]        -0.2425      0.133     -1.828      0.068      -0.502       0.017
C(firm_id)[T.F156]        -0.1330      0.197     -0.675      0.500      -0.519       0.253
C(firm_id)[T.F157]        -0.1807      0.103     -1.760      0.078      -0.382       0.021
C(firm_id)[T.F158]        -0.2275      0.036     -6.350      0.000      -0.298      -0.157
C(firm_id)[T.F159]        -0.2216      0.037     -6.049      0.000      -0.293      -0.150
C(firm_id)[T.F160]        -0.2786      0.074     -3.766      0.000      -0.424      -0.134
C(firm_id)[T.F161]        -0.1964      0.186     -1.057      0.290      -0.560       0.168
C(firm_id)[T.F162]        -0.2494      0.143     -1.741      0.082      -0.530       0.031
C(firm_id)[T.F163]        -0.1084      0.308     -0.352      0.725      -0.712       0.495
C(firm_id)[T.F164]        -0.2158      0.030     -7.298      0.000      -0.274      -0.158
C(firm_id)[T.F165]        -0.1514      0.200     -0.756      0.449      -0.544       0.241
C(firm_id)[T.F166]        -0.1177      0.358     -0.329      0.742      -0.820       0.584
C(firm_id)[T.F167]        -0.0753      0.409     -0.184      0.854      -0.878       0.727
C(firm_id)[T.F168]        -0.0957      0.398     -0.241      0.810      -0.875       0.684
C(firm_id)[T.F169]        -0.1561      0.246     -0.635      0.526      -0.638       0.326
C(firm_id)[T.F170]        -0.1358      0.238     -0.571      0.568      -0.602       0.331
C(firm_id)[T.F171]        -0.1378      0.118     -1.166      0.244      -0.370       0.094
C(firm_id)[T.F172]        -0.0995      0.154     -0.647      0.517      -0.401       0.202
C(firm_id)[T.F173]        -0.0885      0.145     -0.609      0.542      -0.373       0.196
C(firm_id)[T.F174]        -0.0864      0.259     -0.334      0.738      -0.593       0.420
C(firm_id)[T.F175]        -0.1098      0.361     -0.304      0.761      -0.817       0.597
C(firm_id)[T.F176]        -0.0581      0.383     -0.152      0.879      -0.810       0.693
C(firm_id)[T.F177]        -0.0278      0.418     -0.067      0.947      -0.847       0.791
C(firm_id)[T.F178]        -0.0174      0.248     -0.070      0.944      -0.503       0.468
C(firm_id)[T.F179]        -0.1448      0.299     -0.484      0.628      -0.730       0.441
C(firm_id)[T.F180]         0.0108      0.506      0.021      0.983      -0.981       1.002
C(firm_id)[T.F181]        -0.0132      0.250     -0.053      0.958      -0.504       0.477
C(firm_id)[T.F182]        -0.0598      0.206     -0.291      0.771      -0.463       0.343
C(firm_id)[T.F183]        -0.0556      0.428     -0.130      0.897      -0.894       0.783
C(firm_id)[T.F184]        -0.1471      0.243     -0.605      0.545      -0.624       0.330
C(firm_id)[T.F185]         0.0471      0.529      0.089      0.929      -0.990       1.084
C(firm_id)[T.F186]        -0.1613      0.232     -0.697      0.486      -0.615       0.292
C(firm_id)[T.F187]         0.0057      0.451      0.013      0.990      -0.878       0.889
C(firm_id)[T.F188]        -0.1701      0.311     -0.547      0.585      -0.780       0.440
C(firm_id)[T.F189]        -0.0291      0.540     -0.054      0.957      -1.088       1.029
C(firm_id)[T.F190]        -0.0324      0.388     -0.084      0.933      -0.792       0.727
C(firm_id)[T.F191]        -0.1302      0.152     -0.856      0.392      -0.428       0.168
C(firm_id)[T.F192]        -0.1128      0.280     -0.402      0.687      -0.662       0.437
C(firm_id)[T.F193]        -0.1482      0.298     -0.498      0.618      -0.732       0.435
C(firm_id)[T.F194]        -0.0694      0.323     -0.215      0.830      -0.703       0.564
C(firm_id)[T.F195]        -0.1605      0.218     -0.736      0.462      -0.588       0.267
C(firm_id)[T.F196]        -0.0949      0.366     -0.259      0.795      -0.813       0.623
C(firm_id)[T.F197]        -0.1464      0.259     -0.566      0.571      -0.653       0.361
C(firm_id)[T.F198]         0.0113      0.438      0.026      0.979      -0.848       0.870
C(firm_id)[T.F199]         0.0566      0.605      0.094      0.925      -1.129       1.242
C(fiscal_year)[T.2024]    -0.0037      0.010     -0.359      0.720      -0.024       0.017
C(fiscal_year)[T.2025]     0.0051      0.020      0.259      0.796      -0.034       0.044
policy_rate_fye           -0.0037      0.006     -0.588      0.557      -0.016       0.009
leverage_lag              -0.1036      0.119     -0.871      0.384      -0.337       0.129
rate_x_leverage_lag        0.0225      0.018      1.244      0.213      -0.013       0.058
size_ln_assets             0.0427      0.125      0.342      0.732      -0.202       0.287
==============================================================================
Omnibus:                      171.779   Durbin-Watson:                   2.424
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            14214.588
Skew:                          -0.210   Prob(JB):                         0.00
Kurtosis:                      27.656   Cond. No.                     1.55e+04
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The condition number is large, 1.55e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [6]:
main_vars = [
    "policy_rate_fye",
    "leverage_lag",
    "rate_x_leverage_lag",
    "size_ln_assets"
]

results_level_roa = pd.DataFrame({
    "coef": model_level_roa.params[main_vars],
    "std_err": model_level_roa.bse[main_vars],
    "t_stat": model_level_roa.tvalues[main_vars],
    "p_value": model_level_roa.pvalues[main_vars]
})

print(results_level_roa)

print("\nN observations :", int(model_level_roa.nobs))
print("R² :", round(model_level_roa.rsquared, 4))
print("Adj. R² :", round(model_level_roa.rsquared_adj, 4))

print("\nCoefficient clé :")
print("rate_x_leverage_lag =", round(model_level_roa.params["rate_x_leverage_lag"], 6))
print("p-value =", round(model_level_roa.pvalues["rate_x_leverage_lag"], 6))

                         coef   std_err    t_stat   p_value
policy_rate_fye     -0.003687  0.006275 -0.587609  0.556795
leverage_lag        -0.103558  0.118897 -0.870986  0.383762
rate_x_leverage_lag  0.022505  0.018084  1.244479  0.213323
size_ln_assets       0.042686  0.124661  0.342415  0.732039

N observations : 561
R² : 0.8004
Adj. R² : 0.6929

Coefficient clé :
rate_x_leverage_lag = 0.022505
p-value = 0.213323

In [7]:
import pandas as pd
import statsmodels.formula.api as smf

file_path = "/content/final_regression_dataset_v2.xlsx"   # adapte si besoin
df = pd.read_excel(file_path, sheet_name="regression_base")

print(df.shape)
df.head()

(781, 30)

,firm_id,ticker,company_name,country,macro_zone,sector,fiscal_year,roa,roa_ebit,interest_coverage,...,ebit,ebitda,interest_expense,net_income,total_assets,total_debt,source_primary,data_quality_score,notes,interest_coverage_raw_backup
0,F001,AAPL,Apple Inc.,United States,US,Technology,2022,0.282924,0.323701,40.749574,...,1.194370e+11,1.305410e+11,2.931000e+09,9.980300e+10,3.527550e+11,1.118240e+11,Yahoo + SEC override,1.000,NaN,40.749574
1,F001,AAPL,Apple Inc.,United States,US,Technology,2023,0.275098,0.323701,29.062039,...,1.143010e+11,1.258200e+11,3.933000e+09,9.699500e+10,3.525830e+11,1.065720e+11,Yahoo + SEC override,1.000,NaN,29.062039
2,F001,AAPL,Apple Inc.,United States,US,Technology,2024,0.256825,0.323701,NaN,...,1.232160e+11,1.346610e+11,NaN,9.373600e+10,3.649800e+11,9.734100e+10,Yahoo + SEC override,0.875,NaN,NaN
3,F001,AAPL,Apple Inc.,United States,US,Technology,2025,0.306894,0.323701,NaN,...,1.330500e+11,1.447480e+11,NaN,1.120100e+11,3.649800e+11,9.128100e+10,Yahoo + SEC override,0.875,NaN,NaN
4,F002,MSFT,Microsoft Corporation,United States,US,Technology,2022,0.121371,0.145157,20.439599,...,5.295900e+10,1.002390e+11,2.591000e+09,4.428100e+10,3.648400e+11,5.551100e+10,Yahoo + SEC override,1.000,NaN,20.439599

In [8]:
reg_cols = [
    "firm_id",
    "fiscal_year",
    "book_leverage",
    "policy_rate_fye",
    "leverage_lag",
    "rate_x_leverage_lag",
    "size_ln_assets"
]

reg_level_lev = df[reg_cols].dropna().copy()

print("Observations:", len(reg_level_lev))
print("Firmes:", reg_level_lev["firm_id"].nunique())
print("Années:", sorted(reg_level_lev["fiscal_year"].unique()))

Observations: 560
Firmes: 190
Années: [np.int64(2023), np.int64(2024), np.int64(2025)]

In [9]:
model_level_lev = smf.ols(
    "book_leverage ~ policy_rate_fye + leverage_lag + rate_x_leverage_lag + size_ln_assets + C(firm_id) + C(fiscal_year)",
    data=reg_level_lev
).fit(cov_type="cluster", cov_kwds={"groups": reg_level_lev["firm_id"]})

print(model_level_lev.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          book_leverage   R-squared:                       0.960
Model:                            OLS   Adj. R-squared:                  0.939
Method:                 Least Squares   F-statistic:                     18.58
Date:                Sun, 05 Apr 2026   Prob (F-statistic):           6.14e-17
Time:                        22:51:52   Log-Likelihood:                 1149.3
No. Observations:                 560   AIC:                            -1907.
Df Residuals:                     364   BIC:                            -1058.
Df Model:                         195
Covariance Type:              cluster
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  2.2261      1.227      1.815      0.070      -0.178       4.630
C(firm_id)[T.F002]        -0.1369      0.034     -4.016      0.000      -0.204      -0.070
C(firm_id)[T.F003]        -0.2314      0.081     -2.844      0.004      -0.391      -0.072
C(firm_id)[T.F004]        -0.1373      0.042     -3.258      0.001      -0.220      -0.055
C(firm_id)[T.F005]        -0.2031      0.056     -3.659      0.000      -0.312      -0.094
C(firm_id)[T.F006]        -0.1721      0.050     -3.418      0.001      -0.271      -0.073
C(firm_id)[T.F007]         0.1034      0.058      1.777      0.076      -0.011       0.217
C(firm_id)[T.F008]         0.3052      0.082      3.732      0.000       0.145       0.466
C(firm_id)[T.F009]        -0.2509      0.079     -3.184      0.001      -0.405      -0.096
C(firm_id)[T.F010]        -0.2864      0.123     -2.330      0.020      -0.527      -0.045
C(firm_id)[T.F011]        -0.2167      0.071     -3.041      0.002      -0.356      -0.077
C(firm_id)[T.F012]         0.0729      0.044      1.651      0.099      -0.014       0.159
C(firm_id)[T.F013]        -0.3652      0.146     -2.497      0.013      -0.652      -0.079
C(firm_id)[T.F014]        -0.2503      0.116     -2.166      0.030      -0.477      -0.024
C(firm_id)[T.F015]        -0.3534      0.103     -3.440      0.001      -0.555      -0.152
C(firm_id)[T.F016]        -0.0631      0.104     -0.605      0.545      -0.267       0.141
C(firm_id)[T.F017]        -0.1560      0.088     -1.780      0.075      -0.328       0.016
C(firm_id)[T.F018]        -0.2637      0.115     -2.286      0.022      -0.490      -0.038
C(firm_id)[T.F019]        -0.2075      0.087     -2.397      0.017      -0.377      -0.038
C(firm_id)[T.F020]        -0.1123      0.140     -0.802      0.422      -0.387       0.162
C(firm_id)[T.F021]        -0.2310      0.135     -1.714      0.086      -0.495       0.033
C(firm_id)[T.F022]        -0.4162      0.145     -2.877      0.004      -0.700      -0.133
C(firm_id)[T.F024]        -0.0668      0.031     -2.161      0.031      -0.127      -0.006
C(firm_id)[T.F025]         0.0116      0.039      0.300      0.764      -0.064       0.088
C(firm_id)[T.F026]         0.2664      0.085      3.140      0.002       0.100       0.433
C(firm_id)[T.F027]        -0.0344      0.065     -0.528      0.597      -0.162       0.093
C(firm_id)[T.F028]        -0.1377      0.045     -3.050      0.002      -0.226      -0.049
C(firm_id)[T.F029]         0.0929      0.046      2.003      0.045       0.002       0.184
C(firm_id)[T.F030]        -0.0191      0.049     -0.388      0.698      -0.115       0.077
C(firm_id)[T.F031]        -0.0165      0.027     -0.608      0.543      -0.070       0.037
C(firm_id)[T.F032]        -0.0204      0.056     -0.368      0.713      -0.129       0.088
C(firm_id)[T.F033]        -0.2069      0.075     -2.741      0.006      -0.355      -0.059
C(firm_id)[T.F034]        -0.1651      0.073     -2.272      0.023      -0.307      -0.023
C(firm_id)[T.F036]        -0.1656      0.101     -1.636      0.102      -0.364       0.033
C(firm_id)[T.F037]        -0.1376      0.096     -1.437      0.151      -0.325       0.050
C(firm_id)[T.F038]         0.2850      0.131      2.181      0.029       0.029       0.541
C(firm_id)[T.F039]         0.0005      0.141      0.003      0.997      -0.276       0.277
C(firm_id)[T.F040]        -0.0575      0.019     -2.952      0.003      -0.096      -0.019
C(firm_id)[T.F041]        -0.1591      0.067     -2.375      0.018      -0.290      -0.028
C(firm_id)[T.F042]        -0.3822      0.125     -3.057      0.002      -0.627      -0.137
C(firm_id)[T.F043]        -0.0565      0.024     -2.402      0.016      -0.103      -0.010
C(firm_id)[T.F044]         0.3287      0.109      3.019      0.003       0.115       0.542
C(firm_id)[T.F045]        -0.1445      0.049     -2.956      0.003      -0.240      -0.049
C(firm_id)[T.F046]        -0.1297      0.087     -1.492      0.136      -0.300       0.041
C(firm_id)[T.F047]        -0.0759      0.031     -2.475      0.013      -0.136      -0.016
C(firm_id)[T.F048]         0.0561      0.017      3.346      0.001       0.023       0.089
C(firm_id)[T.F049]        -0.0590      0.025     -2.382      0.017      -0.108      -0.010
C(firm_id)[T.F050]         0.0730      0.013      5.607      0.000       0.047       0.098
C(firm_id)[T.F051]        -0.2149      0.093     -2.309      0.021      -0.397      -0.033
C(firm_id)[T.F052]         0.1542      0.118      1.306      0.191      -0.077       0.386
C(firm_id)[T.F053]        -0.3829      0.143     -2.673      0.008      -0.664      -0.102
C(firm_id)[T.F054]        -0.2171      0.149     -1.453      0.146      -0.510       0.076
C(firm_id)[T.F055]         0.0556      0.111      0.502      0.616      -0.161       0.273
C(firm_id)[T.F056]        -0.2091      0.105     -1.982      0.047      -0.416      -0.002
C(firm_id)[T.F057]         0.3730      0.127      2.947      0.003       0.125       0.621
C(firm_id)[T.F058]         0.1838      0.081      2.264      0.024       0.025       0.343
C(firm_id)[T.F059]        -0.3494      0.129     -2.715      0.007      -0.602      -0.097
C(firm_id)[T.F060]        -0.2970      0.168     -1.766      0.077      -0.627       0.033
C(firm_id)[T.F061]        -0.1513      0.038     -3.976      0.000      -0.226      -0.077
C(firm_id)[T.F062]        -0.1533      0.087     -1.758      0.079      -0.324       0.018
C(firm_id)[T.F063]        -0.1101      0.054     -2.050      0.040      -0.215      -0.005
C(firm_id)[T.F064]         0.0390      0.058      0.678      0.498      -0.074       0.152
C(firm_id)[T.F065]         0.0545      0.058      0.939      0.348      -0.059       0.168
C(firm_id)[T.F066]         0.3251      0.109      2.980      0.003       0.111       0.539
C(firm_id)[T.F067]        -0.1689      0.090     -1.875      0.061      -0.346       0.008
C(firm_id)[T.F068]        -0.0272      0.137     -0.199      0.842      -0.295       0.241
C(firm_id)[T.F069]        -0.0192      0.060     -0.318      0.750      -0.138       0.099
C(firm_id)[T.F070]         0.2424      0.076      3.196      0.001       0.094       0.391
C(firm_id)[T.F071]        -0.0578      0.074     -0.777      0.437      -0.204       0.088
C(firm_id)[T.F072]        -0.2507      0.093     -2.683      0.007      -0.434      -0.068
C(firm_id)[T.F073]        -0.0811      0.040     -2.042      0.041      -0.159      -0.003
C(firm_id)[T.F074]        -0.0328      0.082     -0.400      0.689      -0.194       0.128
C(firm_id)[T.F075]         0.0116      0.039      0.300      0.764      -0.064       0.088
C(firm_id)[T.F076]        -0.1011      0.075     -1.347      0.178      -0.248       0.046
C(firm_id)[T.F077]         0.0562      0.064      0.875      0.382      -0.070       0.182
C(firm_id)[T.F078]         0.0656      0.076      0.862      0.388      -0.084       0.215
C(firm_id)[T.F079]        -0.0087      0.094     -0.093      0.926      -0.192       0.175
C(firm_id)[T.F080]        -0.1978      0.105     -1.880      0.060      -0.404       0.008
C(firm_id)[T.F081]        -0.1546      0.111     -1.391      0.164      -0.372       0.063
C(firm_id)[T.F082]        -0.2527      0.134     -1.887      0.059      -0.515       0.010
C(firm_id)[T.F083]        -0.3293      0.154     -2.144      0.032      -0.630      -0.028
C(firm_id)[T.F084]        -0.1555      0.122     -1.270      0.204      -0.395       0.084
C(firm_id)[T.F085]        -0.2122      0.137     -1.545      0.122      -0.481       0.057
C(firm_id)[T.F086]        -0.0937      0.069     -1.360      0.174      -0.229       0.041
C(firm_id)[T.F087]        -0.0576      0.102     -0.567      0.571      -0.257       0.142
C(firm_id)[T.F088]        -0.2404      0.094     -2.570      0.010      -0.424      -0.057
C(firm_id)[T.F089]        -0.1736      0.042     -4.124      0.000      -0.256      -0.091
C(firm_id)[T.F090]        -0.2175      0.054     -4.023      0.000      -0.323      -0.112
C(firm_id)[T.F091]         0.5244      0.255      2.055      0.040       0.024       1.025
C(firm_id)[T.F092]         0.1609      0.197      0.818      0.413      -0.225       0.546
C(firm_id)[T.F093]         0.0142      0.102      0.139      0.889      -0.186       0.214
C(firm_id)[T.F095]        -0.0958      0.123     -0.781      0.435      -0.336       0.145
C(firm_id)[T.F096]         0.0928      0.155      0.597      0.550      -0.212       0.397
C(firm_id)[T.F098]         0.4021      0.202      1.993      0.046       0.007       0.798
C(firm_id)[T.F099]        -0.0598      0.096     -0.623      0.533      -0.248       0.128
C(firm_id)[T.F102]        -0.0511      0.075     -0.683      0.495      -0.198       0.096
C(firm_id)[T.F104]        -0.0967      0.101     -0.955      0.339      -0.295       0.102
C(firm_id)[T.F105]        -0.1825      0.078     -2.349      0.019      -0.335      -0.030
C(firm_id)[T.F106]         0.0374      0.136      0.274      0.784      -0.230       0.305
C(firm_id)[T.F107]         0.1650      0.190      0.870      0.384      -0.207       0.537
C(firm_id)[T.F108]         0.1008      0.114      0.884      0.377      -0.123       0.324
C(firm_id)[T.F109]         0.1876      0.160      1.171      0.242      -0.126       0.502
C(firm_id)[T.F110]         0.2903      0.167      1.733      0.083      -0.038       0.619
C(firm_id)[T.F111]        -0.0651      0.021     -3.114      0.002      -0.106      -0.024
C(firm_id)[T.F112]        -0.0861      0.055     -1.556      0.120      -0.195       0.022
C(firm_id)[T.F113]        -0.0022      0.069     -0.032      0.974      -0.137       0.133
C(firm_id)[T.F114]        -0.0709      0.139     -0.509      0.611      -0.344       0.202
C(firm_id)[T.F115]        -0.0438      0.021     -2.076      0.038      -0.085      -0.002
C(firm_id)[T.F116]        -0.1098      0.080     -1.368      0.171      -0.267       0.048
C(firm_id)[T.F117]         0.0624      0.091      0.683      0.494      -0.117       0.241
C(firm_id)[T.F118]        -0.0334      0.051     -0.658      0.511      -0.133       0.066
C(firm_id)[T.F119]        -0.1343      0.117     -1.149      0.251      -0.363       0.095
C(firm_id)[T.F120]        -0.2043      0.070     -2.913      0.004      -0.342      -0.067
C(firm_id)[T.F121]        -0.0721      0.053     -1.349      0.177      -0.177       0.033
C(firm_id)[T.F122]        -0.1291      0.082     -1.575      0.115      -0.290       0.032
C(firm_id)[T.F123]         0.0700      0.045      1.556      0.120      -0.018       0.158
C(firm_id)[T.F124]        -0.2087      0.120     -1.736      0.083      -0.444       0.027
C(firm_id)[T.F125]        -0.2189      0.125     -1.754      0.079      -0.464       0.026
C(firm_id)[T.F126]        -0.0829      0.104     -0.800      0.423      -0.286       0.120
C(firm_id)[T.F127]        -0.0422      0.082     -0.515      0.607      -0.203       0.118
C(firm_id)[T.F128]        -0.1062      0.068     -1.573      0.116      -0.239       0.026
C(firm_id)[T.F129]         0.1340      0.073      1.824      0.068      -0.010       0.278
C(firm_id)[T.F130]        -0.3288      0.142     -2.308      0.021      -0.608      -0.050
C(firm_id)[T.F131]        -0.1992      0.078     -2.552      0.011      -0.352      -0.046
C(firm_id)[T.F132]        -0.2101      0.075     -2.789      0.005      -0.358      -0.062
C(firm_id)[T.F133]        -0.4497      0.165     -2.718      0.007      -0.774      -0.125
C(firm_id)[T.F134]        -0.1653      0.148     -1.116      0.265      -0.456       0.125
C(firm_id)[T.F135]        -0.3127      0.109     -2.866      0.004      -0.527      -0.099
C(firm_id)[T.F136]        -0.4130      0.135     -3.062      0.002      -0.677      -0.149
C(firm_id)[T.F138]        -0.2207      0.159     -1.387      0.165      -0.533       0.091
C(firm_id)[T.F140]         0.1028      0.082      1.248      0.212      -0.059       0.264
C(firm_id)[T.F141]        -0.0741      0.045     -1.659      0.097      -0.162       0.013
C(firm_id)[T.F142]        -0.3820      0.144     -2.649      0.008      -0.665      -0.099
C(firm_id)[T.F143]        -0.2415      0.099     -2.430      0.015      -0.436      -0.047
C(firm_id)[T.F144]        -0.2653      0.076     -3.514      0.000      -0.413      -0.117
C(firm_id)[T.F145]        -0.1186      0.033     -3.574      0.000      -0.184      -0.054
C(firm_id)[T.F146]        -0.2054      0.066     -3.131      0.002      -0.334      -0.077
C(firm_id)[T.F147]        -0.1549      0.087     -1.778      0.075      -0.326       0.016
C(firm_id)[T.F148]        -0.1692      0.093     -1.824      0.068      -0.351       0.013
C(firm_id)[T.F149]        -0.1901      0.121     -1.572      0.116      -0.427       0.047
C(firm_id)[T.F150]        -0.0761      0.050     -1.519      0.129      -0.174       0.022
C(firm_id)[T.F151]        -0.2480      0.110     -2.258      0.024      -0.463      -0.033
C(firm_id)[T.F152]        -0.1052      0.101     -1.044      0.296      -0.303       0.092
C(firm_id)[T.F153]        -0.2603      0.101     -2.587      0.010      -0.457      -0.063
C(firm_id)[T.F154]        -0.1657      0.084     -1.977      0.048      -0.330      -0.001
C(firm_id)[T.F155]         0.1973      0.061      3.249      0.001       0.078       0.316
C(firm_id)[T.F156]        -0.2695      0.089     -3.016      0.003      -0.445      -0.094
C(firm_id)[T.F157]        -0.0109      0.039     -0.282      0.778      -0.087       0.065
C(firm_id)[T.F158]         0.0128      0.017      0.750      0.454      -0.021       0.046
C(firm_id)[T.F159]         0.0367      0.017      2.211      0.027       0.004       0.069
C(firm_id)[T.F160]         0.0767      0.027      2.822      0.005       0.023       0.130
C(firm_id)[T.F161]        -0.0944      0.072     -1.318      0.187      -0.235       0.046
C(firm_id)[T.F162]      5.235e-05      0.052      0.001      0.999      -0.102       0.102
C(firm_id)[T.F163]        -0.2608      0.123     -2.125      0.034      -0.501      -0.020
C(firm_id)[T.F164]         0.1903      0.038      4.984      0.000       0.115       0.265
C(firm_id)[T.F165]        -0.0795      0.075     -1.064      0.287      -0.226       0.067
C(firm_id)[T.F166]        -0.2033      0.132     -1.539      0.124      -0.462       0.056
C(firm_id)[T.F167]        -0.5128      0.180     -2.853      0.004      -0.865      -0.161
C(firm_id)[T.F168]        -0.3762      0.159     -2.366      0.018      -0.688      -0.065
C(firm_id)[T.F169]        -0.4095      0.125     -3.271      0.001      -0.655      -0.164
C(firm_id)[T.F170]        -0.2176      0.096     -2.256      0.024      -0.407      -0.029
C(firm_id)[T.F171]         0.0998      0.049      2.051      0.040       0.004       0.195
C(firm_id)[T.F172]        -0.0311      0.060     -0.518      0.604      -0.149       0.087
C(firm_id)[T.F173]        -0.0742      0.062     -1.196      0.232      -0.196       0.047
C(firm_id)[T.F174]        -0.2355      0.108     -2.179      0.029      -0.447      -0.024
C(firm_id)[T.F175]        -0.2758      0.145     -1.900      0.057      -0.560       0.009
C(firm_id)[T.F176]        -0.1366      0.140     -0.974      0.330      -0.411       0.138
C(firm_id)[T.F177]        -0.1233      0.150     -0.822      0.411      -0.417       0.171
C(firm_id)[T.F178]        -0.1817      0.100     -1.818      0.069      -0.378       0.014
C(firm_id)[T.F179]        -0.3949      0.133     -2.975      0.003      -0.655      -0.135
C(firm_id)[T.F180]        -0.2685      0.188     -1.426      0.154      -0.638       0.100
C(firm_id)[T.F181]        -0.3274      0.113     -2.901      0.004      -0.549      -0.106
C(firm_id)[T.F182]        -0.1530      0.081     -1.884      0.060      -0.312       0.006
C(firm_id)[T.F183]        -0.5105      0.185     -2.765      0.006      -0.872      -0.149
C(firm_id)[T.F184]        -0.0401      0.087     -0.461      0.645      -0.211       0.130
C(firm_id)[T.F185]        -0.5868      0.222     -2.647      0.008      -1.021      -0.152
C(firm_id)[T.F186]        -0.0781      0.085     -0.919      0.358      -0.245       0.089
C(firm_id)[T.F187]        -0.0886      0.160     -0.553      0.580      -0.403       0.225
C(firm_id)[T.F188]        -0.1955      0.119     -1.645      0.100      -0.429       0.037
C(firm_id)[T.F189]        -0.2582      0.198     -1.306      0.191      -0.646       0.129
C(firm_id)[T.F190]        -0.3179      0.150     -2.126      0.034      -0.611      -0.025
C(firm_id)[T.F191]        -0.1475      0.065     -2.273      0.023      -0.275      -0.020
C(firm_id)[T.F192]        -0.1211      0.100     -1.209      0.227      -0.317       0.075
C(firm_id)[T.F193]         0.0448      0.105      0.428      0.669      -0.161       0.250
C(firm_id)[T.F194]        -0.0510      0.113     -0.451      0.652      -0.273       0.171
C(firm_id)[T.F195]        -0.2310      0.095     -2.439      0.015      -0.417      -0.045
C(firm_id)[T.F196]         0.0138      0.128      0.108      0.914      -0.238       0.265
C(firm_id)[T.F197]        -0.0498      0.092     -0.545      0.586      -0.229       0.130
C(firm_id)[T.F198]        -0.3053      0.162     -1.881      0.060      -0.623       0.013
C(firm_id)[T.F199]        -0.5444      0.236     -2.307      0.021      -1.007      -0.082
C(fiscal_year)[T.2024]     0.0036      0.006      0.563      0.574      -0.009       0.016
C(fiscal_year)[T.2025]     0.0014      0.010      0.139      0.890      -0.018       0.021
policy_rate_fye           -0.0056      0.008     -0.699      0.485      -0.021       0.010
leverage_lag              -0.0431      0.243     -0.178      0.859      -0.519       0.433
rate_x_leverage_lag        0.0117      0.020      0.587      0.557      -0.027       0.051
size_ln_assets            -0.0726      0.045     -1.608      0.108      -0.161       0.016
==============================================================================
Omnibus:                      264.403   Durbin-Watson:                   2.683
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            18611.569
Skew:                           1.192   Prob(JB):                         0.00
Kurtosis:                      31.142   Cond. No.                     1.54e+04
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The condition number is large, 1.54e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 195, but rank is 6
  warnings.warn('covariance of constraints does not have full '

In [10]:
main_vars = [
    "policy_rate_fye",
    "leverage_lag",
    "rate_x_leverage_lag",
    "size_ln_assets"
]

results_level_lev = pd.DataFrame({
    "coef": model_level_lev.params[main_vars],
    "std_err": model_level_lev.bse[main_vars],
    "t_stat": model_level_lev.tvalues[main_vars],
    "p_value": model_level_lev.pvalues[main_vars]
})

print(results_level_lev)

print("\nN observations :", int(model_level_lev.nobs))
print("R² :", round(model_level_lev.rsquared, 4))
print("Adj. R² :", round(model_level_lev.rsquared_adj, 4))

print("\nCoefficient clé :")
print("rate_x_leverage_lag =", round(model_level_lev.params["rate_x_leverage_lag"], 6))
print("p-value =", round(model_level_lev.pvalues["rate_x_leverage_lag"], 6))

                         coef   std_err    t_stat   p_value
policy_rate_fye     -0.005598  0.008010 -0.698882  0.484626
leverage_lag        -0.043128  0.242826 -0.177610  0.859029
rate_x_leverage_lag  0.011685  0.019912  0.586831  0.557317
size_ln_assets      -0.072617  0.045162 -1.607919  0.107853

N observations : 560
R² : 0.9601
Adj. R² : 0.9388

Coefficient clé :
rate_x_leverage_lag = 0.011685
p-value = 0.557317